### ISSUE TITLE
Trend Metrics timezone

### ISSUE THREAD

**Issue by xtrime-ru** [laravel/nova-issues#1136]
- Laravel Version: 5.7.17
- Nova Version: 1.2.0
- PHP Version: 7.2

### Description:
I use 'Europe\Moscow' timezone (UTC+3) in app, in mariadb and on server. Everything works as expected except Trend Metrics. 
For example: countByDays Trend based on `created_at` field adds 3 hours for all dates. But db connection already in correct timezone, so this is makes all dates incorrect (double add timezone offset).

![2018-12-16 23 32 09](https://user-images.githubusercontent.com/34161928/50058546-09529600-018b-11e9-8faa-7ee91d80080a.png)

This screenshot is made December,16 at 23:30 by local time, and time at column is correct, but Trend Metrics adds 3 hours and sends some rows in future.

### Steps To Reproduce:
1. set 'Europe/Moscow' for system
1. set system timezone for mariadb (by default its already system)
1. set 'Europe/Moscow' timezone in config/app.php
1. Add Trend Metric to any model.

**Comment by xtrime-ru** [comment]
I found temporary solution:

add following code to  `\App\Providers\NovaServiceProvider::boot()`:
```
        parent::boot();

        Nova::userTimezone(function (Request $request) {
            return '+00:00';
        });
```

It fixes bug, but adds some error messages in console of browser. All dates and metrics, however, work correctly.  

![2019-01-22 1 12 07](https://user-images.githubusercontent.com/34161928/51501391-bf407e00-1de2-11e9-87ae-3d050416f907.png)

![2019-01-22 1 13 12](https://user-images.githubusercontent.com/34161928/51501422-e72fe180-1de2-11e9-8774-fa71b5fb29aa.png)

**Comment by dkulyk** [comment]
http://php.net/manual/en/timezones.php

**Comment by dkulyk** [comment]
`Europe\Moscow` => `Europe/Moscow`
http://php.net/manual/en/timezones.europe.php

**Comment by xtrime-ru** [comment]
> `Europe\Moscow` => `Europe/Moscow`
> http://php.net/manual/en/timezones.europe.php
> 
> `+00:00` is wrong timezone. You need to use `UTC` instead.

1. ![2019-01-22 1 40 04](https://user-images.githubusercontent.com/34161928/51502337-bea9e680-1de6-11e9-8c51-7973d53d6c24.png)
1. Fix is working because timezone is incorrect. If UTC is set in `\App\Providers\NovaServiceProvider::boot()`, then other dates become incorrect.

**Comment by dkulyk** [comment]
@davidhemphill I think in offset method need to return difference between User TZ and App TZ

**Comment by rverrips** [comment]
Tried with updated Laravel, Nova and PHP

> Laravel Version: 5.7.26
> Nova Version: 1.3.2
> PHP Version: 7.3.2

Still same issue persisting. 

Also, when I tried the possible fix, I get a exception error as attached

<img width="1370" alt="screen shot 2019-02-18 at 3 06 47 pm" src="https://user-images.githubusercontent.com/749015/52988182-dcf20a80-33c3-11e9-8277-9c42e0c9c93c.png">

**Comment by xtrime-ru** [comment]
> Update to [#1136 (comment)](https://github.com/laravel/nova-issues/issues/1136#issuecomment-456148142)
> Tried with updated Laravel, Nova and PHP
> 
> Laravel Version: 5.7.26
> Nova Version: 1.3.2
> PHP Version: 7.3.2
> 
> Still same issue persisting.
> 
> Also, when I tried the possible fix, I get a exception error as attached for what it's worth.
> 
> <img alt="screen shot 2019-02-18 at 9 23 25 pm" width="979" src="https://user-images.githubusercontent.com/749015/52988301-47a34600-33c4-11e9-81b5-a5f36a805101.png">

Oh, it's my fault. IDE collapsed 'use' block. I will update my answer with full path to 'Request' class. Thank you for feedback.

**Comment by rverrips** [comment]
***Awesome!***  Thanks @xtrime-ru - The temporary fix is working for me now ...

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by infister** [comment]
This problem still exists on Nova 2 (chart is loading with timezone param, when it is removed, problem solved)
-> nova/src/Metrics/Trend.php, 

```
$timezone = $request->timezone;
```
to
```
$timezone = null;
```

**Comment by jbrooksuk** [comment]
Please open a new ticket if the issue still persists.

**Comment by infister** [comment]
Then open one, I have already fixed it by myself and have no interest in wasting my time.

**Comment by ivanzhang2** [comment]
@infister  how you fixed it ? by use "$timezone = null;" ?  seems not working ...

**Comment by tumainimosha** [comment]
Laravel Version: 7.11.0
Nova Version: 3.4.0
PHP Version: 7.4.6

Seems this issue is still present in latest version of nova.

### Background

After digging down in nova source code, I think I found the issue at `src/Metrics/TrendDateExpression.php` at function `offset()`

```php
    public function offset()
    {
        if ($this->timezone) {
            return (new DateTime(Chronos::now()->format('Y-m-d H:i:s'), new DateTimeZone($this->timezone)))->getOffset() / 60 / 60;
        }

        return 0;
    }
```

`offset()` calculates timezone offset to be applied on datetime columns used in aggregations. It returns the Datetime offset of the current timezone and applies it as a shift(+/-) towards the time column stored in DB.

If your app is using `UTC` timezone this works fine as dates are stored in db as UTC time. 

### Issue
Default laravel behaviour is date is stored in db with same timezone as app timezone see (this)[https://github.com/laravel/framework/issues/1841]. If your app uses a different timezone then the offset calculation for database stored times needs to be calculated against your app timezone and not against UTC

### Proposed Solution

Proposed changes to `src/Metrics/TrendDateExpression.php` 

```php
    public function offset()
    {
        if ($this->timezone) {
            $userTimezoneOffset = (new DateTime(Chronos::now()->format('Y-m-d H:i:s'), new DateTimeZone($this->timezone)))->getOffset() / 60 / 60;

            // Take into account system timezone thats already factored in database stored time
            $dbTimezone = config('app.timezone');
            $dbTimezoneOffset = (new DateTime(Chronos::now()->format('Y-m-d H:i:s'), new DateTimeZone($systemTimezone)))->getOffset() / 60 / 60;

            return $userTimezoneOffset - $dbTimezoneOffset;
        }

        return 0;
    }
```
