### ISSUE TITLE
Unable to set placeholder for DateTime field

### ISSUE THREAD

**Issue by BenSampo** [laravel/nova-issues#1137]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2

### Description:
I'm unable to set the placeholder text for a DateTime field.

The default placeholder is the current date and time. Because I have a nullable DateTime field, this doesn't make sense, and I would like to change the placeholder text.

### Steps To Reproduce:
```php
DateTime::make('Expires At')->nullable()->withMeta([
  'value' => null,
  'placeholder' => 'Select expiry date', // Doesn't work
]);
```

**Comment by dkulyk** [comment]
PR has been sent to upstream.

**Comment by dkulyk** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by EidoKh** [comment]
please I also need a solution for this problem

**Comment by mstaack** [comment]
this still happens for me with the latest version on a date field.

**Comment by bluec** [comment]
Still happens for me in 3.32, using `->placeholder('Whatever')` has no effect on DateTime field
