### ISSUE TITLE
Question mark issue

### ISSUE THREAD

**Issue by charlielangridge** [laravel/nova-issues#117]
When I try to type a ? (Windows 10 / Chrome), it always jumps to the global search bar - is there a way to disable this, either globally or (preferably) when filling in a field

**Comment by bradykeeling** [comment]
I'm still having this same issue using Nova version 1.0.8. (macOS 10.13.6 / Chrome)

**Comment by bradykeeling** [comment]
Also, this is specific to the Trix editor.

**Comment by richfoxton** [comment]
It also happens when using other WYSIWG editors, especially where they are operating in 'inline' mode.

**Comment by Jam0r85** [comment]
Happens when typing 'e' as well into a field.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by charger513** [comment]
The problem is still present with other WYSIWG editors in Nova 1.1.3

**Comment by davidhemphill** [comment]
What other editors? This is fixed with both the Trix and Markdown fields.

**Comment by charger513** [comment]
> What other editors? This is fixed with both the Trix and Markdown fields.

https://github.com/chmln/vue-wysiwyg
https://github.com/ankurk91/vue-trumbowyg

**Comment by davidhemphill** [comment]
These editors need to stop propagation of those events up to the global handler. This is not a bug in Nova.

**Comment by reado** [comment]
> These editors need to stop propagation of those events up to the global handler. This is not a bug in Nova.

I totally get that the vue component needs to stop propation of those events, @davidhemphill do you mind elaborating a little bit more?  Like in the case of the Trix editor, is there something straight forward that we can put into our components to prevent this?

Any help would be appreciated.  Thanks!

**Comment by davidhemphill** [comment]
Sure. If you check out the source to `Trix.vue` you'll see this template block:

```vue
<template>
    <trix-editor
        ref="theEditor"
        @keydown.stop
        @trix-change="handleChange"
        @trix-initialize="initialize"
        @trix-attachment-add="handleAddFile"
        @trix-attachment-remove="handleRemoveFile"
        @trix-file-accept="handleFileAccept"
        :value="value"
        :placeholder="placeholder"
        class="trix-content"
    />
</template>
```

In there we're listening for the `keydown` event from the `trix-editor` and using `@keydown.stop` to stop those events from bubbling all the way to the document handler. This keeps those keystrokes from triggering our global search along with our edit and create resource bindings.

Does that make sense?

**Comment by reado** [comment]
> @keydown.stop

This totally makes sense.. Thank you!  Now it's time to hook it up :D

Thanks again

**Comment by bcorcoran** [comment]
For Tiptap, you must modify the editor config (since it does not emit prosemirror events as vue events) as follows:

```

new Editor({
    ...,
    editorProps: {
        handleKeyDown: (editorView, keyboardEvent) => {
        // Prevent ? or / from triggering Nova global search
        keyboardEvent.stopPropagation();
        }
    }
});

```
