### ISSUE TITLE
Calendar navigation in action closes the window.

### ISSUE THREAD

**Issue by sasureshkumar** [laravel/nova-issues#1183]
- Laravel Version: 5.7
- Nova Version: 1.2
- PHP Version:7.3.0

### Description:
Calendar month navigation in action popup closes itself and re-initiating the action via play button reset the form filled already.

### Steps To Reproduce:
Add a date field to an action. Click the next/previous month navigation button.

![datepicketmonthnavigationclo](https://user-images.githubusercontent.com/493515/50582719-786a0300-0e8a-11e9-91b5-f43684521a75.gif)

**Comment by bonzai** [comment]
This was fixed in 1.2.1.

https://nova.laravel.com/releases

**Comment by uandco** [comment]
Hi, it seems like the bug is back, not sure when it made it back but I'm experiencing the same in Nova 3.31.0.
We recently upgraded from 3.8.4 to 3.31.0.

I just downgraded again to 3.8.4 and the bug is gone so it definitely happened between these 2 version, sorry I can't be more precise at this stage but I'll try different versions to see when the it was re-introduced.

**Comment by crynobone** [comment]
@uandco always create new issue with full reproducing steps.
