### ISSUE TITLE
Pagination Bugs

### ISSUE THREAD

**Issue by cwplus** [laravel/nova-issues#1408]
- Laravel Version: 5.8.2
- Nova Version: 2.0.0
- PHP Version: 7.1.23
- Operating System and Version: macOS 10.14.3
- Browser type and version: google chrome  ( Version 72.0.3626.119 (Build officiel) (64 bits) )

### Description:
When I use pagination type (links), the pagination system does not work, with the fields HasMany and BelongsToMany.

### Steps To Reproduce:
Company:
 --> id
 --> name
--> Offices ( Model Office )
--> Managers ( Collection of User model, type:manager )
--> owner_id ( Model User, type: owner )
...

Office:
--> id
--> name
--> address
--> company_id 
...

User:
 --> id
 --> name
--> type ( enum['admin','owner','manager','basic_user'])
...

In Company model:
```
...
    public function managers()
    {
        return $this->hasMany(User::class)->where('type','manager');
    }

    public function offices()
    {
        return $this->hasMany(Office::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class,'owner_id');
    }
...
```

In Company Nova model:
```
...
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Text::make('Name')
                ->rules("required","max:254","min:3"),

            Text::make('Phone')
                ->sortable()
                ->rules('max:25'),

            Text::make('Email')
                ->sortable()
                ->rules('required', 'email', 'max:254')
                ->creationRules('unique:companies,email')
                ->updateRules('unique:companies,email,{{resourceId}}'),

            Text::make('Url')->sortable()
                ->rules('required','url')->hideFromIndex(),


            HasMany::make('Managers','managers',User::class)->onlyOnDetail(),

            HasMany::make('Offices')->onlyOnDetail(),
            
            Number::make("Managers",function () {
                return count($this->managers);
            })->onlyOnIndex()->sortable(),

            Number::make("Offices",function () {
                return count($this->offices);
            })->onlyOnIndex()->sortable(),
        ];
    }
...
```

Compared to my example, when I click on the model company detail view, the pagination (type: links), does not work as it should, when the total number is smaller than 25, yet the number displayed per page is 5, in this case.

Screenshots:
Example 1: Total < 25, 5 elements per page
<img width="1834" alt="example total 25" src="https://user-images.githubusercontent.com/5727109/53698993-e7f56380-3de3-11e9-8a4e-621a250263d4.png">

Example 2 :  Total > 25, 5 elements per page, first page
<img width="1834" alt="example total 25" src="https://user-images.githubusercontent.com/5727109/53699001-f5aae900-3de3-11e9-9761-52d16bf533a7.png">

Example 3 :  Total > 25, 5 elements per page, second page
<img width="1834" alt="example total 25 page 2" src="https://user-images.githubusercontent.com/5727109/53699005-fcd1f700-3de3-11e9-9447-cccecab4dd7a.png">

**Comment by dkulyk** [comment]
PR was sent to upstream

**Comment by cwplus** [comment]
We have another bug, for pagination type: simple
<img width="1834" alt="pagination simple" src="https://user-images.githubusercontent.com/5727109/53703242-f6597480-3e0f-11e9-8780-ddc4f140004f.png">

**Comment by cwplus** [comment]
@dkulyk thanks, it works 👍

**Comment by Phr33d0m** [comment]
> @dkulyk thanks, it works

Where did you get the PR from to test that it works?

**Comment by aronquiray** [comment]
@dkulyk @cwplus 
may I ask. how can I paginate? Like for ex. for users, I seed it to 2000 but it doesn't paginate.

On the documentation, it says. 
"By default, Nova Resources are displayed using the "simple" style. However, you may customize this to use the "links" style. You can enable this by setting the pagination option in your app/nova.php configuration file:" 

I did update my app/nova.php (added 'pagination' => 'links',) as it was stated on the docu, but no pagination happened. 

is there any commands on the resource to enable this?

**Comment by cwplus** [comment]
![enregistrement de l ecran 2019-03-07 a 16 23 08 3](https://user-images.githubusercontent.com/5727109/53968518-83921700-40f7-11e9-9b3a-39d937bbbb43.gif)

**Comment by aronquiray** [comment]
Hi @cwplus 

I've already updated my nova files. but it seems doesn't work. Do I have to recompile anything? 

![gif1](https://user-images.githubusercontent.com/13714092/53971517-033fd600-4138-11e9-8c53-e6143af5c60d.gif)

**Comment by plakhin** [comment]
Don't forget to publish assets with `php artisan nova: publish`

**Comment by aronquiray** [comment]
@plakhin  already done that..  still doesn't give me a pagination

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by cwplus** [comment]
try to make a new installation with nova: 2. *
maybe, it's going to fix the bug

**Comment by dkulyk** [comment]
Next release not yet released

**Comment by rdarcy1** [comment]
Sorry to bump a closed issue, but is there any news on when the fix will be released? Causing quite an issue for one of our sites.

**Comment by Cannonb4ll** [comment]
Having the same issue here.

**Comment by dkulyk** [comment]
It was fixed in 2.0.1.

**Comment by Cannonb4ll** [comment]
@dkulyk I am still experiencing the issue where the pagination is 'disabled' whereas I have enough records to paginate. I cannot move to another page.

**Comment by dkulyk** [comment]
You should make another issue for it.

**Comment by patricktsg** [comment]
I am experiencing the exact same issue after updating to 2.0.1 

I have 60 related records.
Page one shows 1-5 of 60
Click page 2 and it jumps to records 26-X

It looks like the pagination defaults to the '25' default records you'd see on a parent resource.

**Comment by rdarcy1** [comment]
@patricktsg Have you run `php artisan nova:publish` or `php artisan nova:publish --force`?

**Comment by patricktsg** [comment]
@rdarcy1 Yep and it still didn't work. I i have 10 related records and set $perPageViaRelationship = 10 it displays 1-10 of 10 with pagination disabled.

If I set it to '5' it shows 1-5 of 10 with pagination disabled.

If I set it to '100' (where I have a 60 big record set) it's giving me 1-60 of 60 but showing three pages pagination links. Clicking pagination link for page two or three then takes me to a page where it shows the create option.

![Screen Shot 2019-04-17 at 12 20 40](https://user-images.githubusercontent.com/16956839/56284121-7d865180-610b-11e9-843e-588b9436590c.png)
![Screen Shot 2019-04-17 at 12 21 39](https://user-images.githubusercontent.com/16956839/56284131-81b26f00-610b-11e9-8eb8-b4fc8a1a45d1.png)
