### ISSUE TITLE
`SingularOrPlural` Should not handle symbols

### ISSUE THREAD

**Issue by latrell** [laravel/nova-issues#1847]
- Laravel Version: 5.8.33
- Nova Version: 2.1.0
- PHP Version: 7.3
- Database Driver and Version: MariaDB 10.4.6
- Operating System and Version: CentOS 7.5
- Browser type and version: Chrome 76.0.3809.100

### Description

In Metrics I want to count the percentage trend, so use `suffix` to add the `%` suffix, but actually show `%s`.

### Steps To Reproduce

* Create a Metrics of type `Value` or `Trend`
* return $this->result(100)->previous(50)**->suffix('%')**;

**Comment by jbrooksuk** [comment]
I've had a look at the [inflector-js](https://www.npmjs.com/package/inflector-js) package that Nova uses under the hood and it does not seem to care about symbols. I then swapped inflector-js for [inflected](https://www.npmjs.com/package/inflected) and that has the same issue.

I think we'd need to check against a list of known symbols and simply return that instead of "inflecting" it.

**Comment by jbrooksuk** [comment]
Alternatively, we make it so that the `suffix` method has a second argument for whether or not to run the `SingularOrPlural` method.

**Comment by pelmered** [comment]
@jbrooksuk A second parameter that gives us full control would be the best thing by far. A lit of know symbols would be very inflexible and a not so nice to maintain.

**Comment by pelmered** [comment]
I can confirm that it works with Nova v2.2.0 if you add `->withoutSuffixInflection()` to the returned `ValueResult`. 
Thanks for the fix!

**Comment by jbrooksuk** [comment]
:+1:

**Comment by latrell** [comment]
**This issue has not been completely fixed.**

<img width="442" alt="WX20190906-013236@2x" src="https://user-images.githubusercontent.com/6267962/64364780-3d862380-d046-11e9-83c1-5b0d4f5d6b14.png">

**Comment by pelmered** [comment]
I have the same problem as @latrell for trend metrics. For the value metrics and the latest value for trend metrics it works good, but not in the tooltip/hover in the trend graph.

**Comment by jbrooksuk** [comment]
Hmm, thought I covered it all. Will fix when I’m back.

**Comment by danielbachhuber** [comment]
I tried `->withoutSuffixInflection()` in Nova v2.3.1 and am still seeing the issue in the tooltip:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/36432/65332531-b7083080-db73-11e9-8746-e552bde9f8ae.png">

**Comment by pelmered** [comment]
@jbrooksuk The number formatting isn't working in the tooltip either. 
![Screenshot 2019-09-23 12 47 40](https://user-images.githubusercontent.com/680058/65420101-99033000-de00-11e9-87f7-341bf245bcac.png)

**Comment by jbrooksuk** [comment]
I'm going to split this new issue out as the core of this issue is fixed :)

**Comment by Monamoxie** [comment]
For anyone still having this issue, you should do this:

`->suffix($arg)
->withoutSuffixInflection()
`

Pass the value you want to the suffix method, then call the withoutSuffixInflection() as well. The latter takes no argument
