### ISSUE TITLE
Duplicate requests when saving form

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/nova-issues#1999]
- Laravel Version: 6.1
- Nova Version: 2.4
- PHP Version: 7.2
- Database Driver and Version: MySQL 8.0.16
- Operating System and Version: macOS 10.13
- Browser type and version: Firefox 69.0.1

### Description

Duplicate of #1994 as requested. Note: this issue appears to specifically affect Firefox.

As described in #1994, upon submitting any form view the `POST` request is sent twice:

![Screen Shot 2019-10-02 at 5 39 21 PM](https://user-images.githubusercontent.com/18192441/66084820-91006a00-e53d-11e9-877d-3ec3dfad5905.png)

On the Create form, this means the resource is in fact created twice:

![Screen Shot 2019-10-02 at 6 03 49 PM](https://user-images.githubusercontent.com/18192441/66085418-205a4d00-e53f-11e9-89e3-e44fb1971722.png)

Additionally, on the Update form, after submitting via "Update & Continue Editing" once, clicking on either submit button again results in two JS errors with a `e.t0.response is undefined` message:

![Screen Shot 2019-10-02 at 6 04 57 PM](https://user-images.githubusercontent.com/18192441/66085613-b9896380-e53f-11e9-914f-b86dd23ca710.png)

After rebuilding and republishing Nova's assets in order to un-minify them, the errors look like this:

![Screen Shot 2019-10-02 at 6 08 46 PM](https://user-images.githubusercontent.com/18192441/66085635-c4dc8f00-e53f-11e9-8529-378729e5814d.png)

### Steps To Reproduce

Completely fresh install of Laravel, Nova, etc, create or update any resource using Firefox.

**Comment by bakerkretzmar** [comment]
It looks to me as though the Update and Create forms are being submitted twice because of `@submit.prevent="updateResource"` on the `form` element. Both buttons have an event listener that also call that method.

Replacing it with `@submit.prevent` is valid according to the Vue docs and appears to resolve this issue because the form is only submitted once.

**Comment by jwktje** [comment]
Just commenting to say; I had the exact same issue. Rolled back to the version before and it didn't occur. 

Also only had this happen in Firefox

**Comment by LorenzoSapora** [comment]
Ditto, above. Firefox (latest), ubuntu 19, laravel 5.8~, nova 2.4.0. Although my error happens to be 

![image](https://user-images.githubusercontent.com/25519274/66129877-a5e60780-e5e8-11e9-97c3-b3610e4b61fb.png)

Saving completes, but it's obviously calling twice, and failing the second one (as it should)

**Comment by baskinvolkan** [comment]
same here..
Firefox (latest), Ubuntu 19.04, Laravel 6, Nova 2.4.0

**Comment by Stephen-McDaniel** [comment]
Seeing the same issue.  Only on Firefox (69.01). 

Works as expected in Safari or Chrome running on OS Mojave 10.14.6

**Comment by BrunoRB** [comment]
Same. 
FF 69.0.1, Nova 2.4.0, Slackware 14.2.

**Comment by ltd300** [comment]
I'm having the same issue with Firefox developer edition an Nova v2.4.0

**Comment by devfaysal** [comment]
Same problem here.
![Screenshot(5)](https://user-images.githubusercontent.com/16212149/66271871-bd412100-e884-11e9-8bf9-34618c320063.png)

**Comment by mikebronner** [comment]
We have been seeing the same issue as well, only in Firefox.

**Comment by jbrooksuk** [comment]
The fix hasn’t been released yet.

**Comment by danielbachhuber** [comment]
I'm seeing this issue too in Nova 2.4.0:

![duplicatedupdate](https://user-images.githubusercontent.com/36432/66587377-2358cd00-eb3f-11e9-9993-e2de69a2078f.gif)

> The fix hasn’t been released yet.

Does this mean:
1. The issue has been fixed, but hasn't been released?
2. The issue hasn't been fixed yet?
3. It's not a known issue (per https://github.com/laravel/nova-issues/issues/1994#issuecomment-537688357)?

**Comment by davidhemphill** [comment]
#1

**Comment by sanderbaas** [comment]
Is it just me, or hasn't this been fixed in v2.5.0?

**Comment by crumb1e** [comment]
Any update on this? Still experiencing this on nova 2.9.2 running Firefox 71.0.
