### ISSUE TITLE
Boolean Filter true default value requires 2 clicks to unselect

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#2026]
- Laravel Version: 5.8.35
- Nova Version: 2.3.1
- PHP Version: 7.3
- Operating System and Version: MacOS 10.14.3
- Browser type and version: Chrome 77

### Description

When creating a Boolean Filter with default values, I find if any of the default values are `true`, eg the checkbox is checked by default, I have to click them twice to unselect them. The first time I click the already selected checkbox, my URL updates in the browser with the encoded filter string, but the checkbox doesnt uncheck and update the results until I click it again

**Comment by jbrooksuk** [comment]
Could you please provide us with a copy of your filter? I'm unable to replicate the issue.

**Comment by matthewjumpsoffbuildings** [comment]
do you mean the code im using? if so heres what i have:
```
<?php

namespace App\Nova\Filters;

use Illuminate\Http\Request;
use Laravel\Nova\Filters\BooleanFilter;

class UnverifiedTrackFilter extends BooleanFilter
{
	public function apply(Request $request, $query, $value)
	{
		$query->where('is_valid', $value['valid']);

		if($value['verified'])
			$query->whereHas('track');
		else
			$query->whereDoesntHave('track');

		return $query;
	}

	public function options(Request $request)
	{
		return [
			"Valid" => "valid",
			"Verified" => "verified"
		];
	}

	public function default()
	{
		return [
			'valid' => true,
			'verified' => false
		];
	}
}
```

**Comment by jbrooksuk** [comment]
Perfect, that's very helpful, thanks!

**Comment by davidhemphill** [comment]
Fixed in laravel/nova@f83c6dbe5bda5c4528e914588f50ade948aff406

**Comment by eithed** [comment]
Could you please tell me which version this is released on / will be released?

Still seeing the buggy behaviour on 2.7.1

**Comment by matthewjumpsoffbuildings** [comment]
ye im still seeing this in 2.7.1 too
