### ISSUE TITLE
Partition Metric CSS break

### ISSUE THREAD

**Issue by Athuli7** [laravel/nova-issues#217]
![screen shot 2018-08-26 at 17 31 37 pm](https://user-images.githubusercontent.com/4718029/44628029-4aae0400-a956-11e8-8f05-832addd11c38.png)

If the number of partitions exceeds the maximum that can be listed, it turns into a scrollable entity, but the graphs moves.

**Comment by davidhemphill** [comment]
This should be fixed in the current releases.

**Comment by arall** [comment]
I think this still happening
![image](https://user-images.githubusercontent.com/1453137/53373423-b39e2500-3955-11e9-84fc-eeb3ba787005.png)

**Comment by rikless** [comment]
have it on 1.3.2

**Comment by Athuli7** [comment]
Still happening.
