### ISSUE TITLE
Edit, delete & action buttons missing from details page when using all Panels as fields

### ISSUE THREAD

**Issue by Andy-Baker** [laravel/nova-issues#219]
This shows the correct details page header buttons:
```
return [
	ID::make()->sortable(),
	new Panel('Data', $this->dataFields()),
];
```
![buttons](https://user-images.githubusercontent.com/1121864/44628883-5c84ac80-a940-11e8-9b88-34b4ef175fcb.png)

---

This does not:
```
return [
	new Panel('Data', $this->dataFields()),
];
```
![nobuttons](https://user-images.githubusercontent.com/1121864/44628886-60b0ca00-a940-11e8-9648-8f77007b080f.png)

**Comment by m-a-k-o** [comment]
I don't see button in details also when I have ID defined inside fields.

**Comment by Andy-Baker** [comment]
Done some more testing, and the issue only happens when the first item in the fields array is a Panel.

**Comment by m-a-k-o** [comment]
Not my case. I don't have panel inside fields and I also included ID but no buttons.

![image](https://user-images.githubusercontent.com/6873535/44630100-e17bc000-a958-11e8-8cf0-d91d69afe357.png)

![image](https://user-images.githubusercontent.com/6873535/44630101-e93b6480-a958-11e8-96cf-acb6fb1242bc.png)

**Comment by lucasromanojf** [comment]
Yeah I never saw these buttons and actions too

**Comment by disitec** [comment]
I just realized that those buttons even exist! Never saw them

**Comment by lucasromanojf** [comment]
This is what is causing this bug (Detail.vue file):

![image](https://user-images.githubusercontent.com/3661610/44658586-be442580-a9d7-11e8-948f-8d037c5476aa.png)

**Comment by disitec** [comment]
wow the whole v-if is relying in a text fragment! Nice catch @lucasromanojf

**Comment by antoniolore** [comment]
@lucasromanojf nice catch!

**Comment by davidhemphill** [comment]
This has been fixed in laravel/nova#79 and will be included in an upcoming release.

**Comment by vernard** [comment]
I'm using v1.3.0 and this is still not fixed.

This doesn't show the action button:
![image](https://user-images.githubusercontent.com/6733673/51077323-f4ace380-16df-11e9-96f9-238a632c1469.png)
![image](https://user-images.githubusercontent.com/6733673/51077333-18702980-16e0-11e9-8b52-f7a9ad5bce81.png)



But this one does:
![image](https://user-images.githubusercontent.com/6733673/51077336-26be4580-16e0-11e9-8521-ce6e75d182e2.png)
![image](https://user-images.githubusercontent.com/6733673/51077338-3178da80-16e0-11e9-9123-a92a950e12f4.png)


Having `hideFromDetail()` on the ID field makes the edit and delete button disappear.
