### ISSUE TITLE
This user may not be associated with this resource.

### ISSUE THREAD

**Issue by kadinho** [laravel/nova-issues#227]
"This user may not be associated with this resource."

Staff resource - belongs to user class

```
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable()->onlyOnDetail(),
            BelongsTo::make('User'),
            Select::make('Employee Function', 'employee_function')
                ->options(StaffModel::EMPLOYEE_FUNCTION_LIST)
                ->displayUsingLabels(),
            Text::make('Employee Number', 'employee_number'),
            Date::make('Birth Date', 'birth_date')->hideFromIndex(),
            Place::make('Address', 'address')->hideFromIndex(),
            Text::make('City', 'city')->hideFromIndex(),
            Text::make('Postal Code', 'postal_code')->hideFromIndex(),
            Country::make('Country', 'country')->hideFromIndex(),
            Country::make('Phone Country', 'phone_country')->hideFromIndex(),
            Text::make('Phone Country', 'phone')->hideFromIndex(),
            Country::make('Mobile Country', 'mobile_country')->hideFromIndex(),
            Text::make('Mobile Country', 'mobile')->hideFromIndex(),
            Status::make('Status', function (){
                return StaffModel::STATUS_LIST[$this->status];
            })->loadingWhen(['waiting', 'running'])
                ->failedWhen(['failed'])
        ];
    }
```
when i try to update i got "This user may not be associated with this resource."

**Comment by ryryan** [comment]
Has this user already got a staff resource? As `BelongsTo` uses a `HasOne` relationship and therefor only allow one record for that user and would cause this error.

**Comment by kenneth-g-flux** [comment]
I've fixed the issue in `/Rules/Relatable.php` (starting on line 67) by adding another check, using an extra method:
```
    /**
     * Determine if the relationship is "full".
     *
     * @param  string  $attribute
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return bool
     */
    protected function relationshipIsFull($attribute, $model)
    {
        $inverseRelation = $this->request->newResource()
                    ->resolveInverseFieldsForAttribute($this->request, $attribute)->first(function ($field) {
                        return $field instanceof HasOne || $field instanceof MorphOne;
                    });

        return $inverseRelation &&
               $model->{$inverseRelation->attribute}()->count() > 0 &&
               $this->relationshipChangedOnUpdate($attribute ,$model);
    }
    
    /**
     * Determine if the relationship will actually be updated, or just stays as it it.
     * 
     * @param string  $attribute
     * @param \Illuminate\Database\Eloquent\Model  $relatedModel
     * @return bool
     */
    protected function relationshipChangedOnUpdate($attribute, $relatedModel)
    {
        if (! $this->request instanceof UpdateResourceRequest) {
            return true;
        }
        
        $model = $this->request->findModelOrFail();
        if (! $model || ! $model->{$attribute}) {
            return true;
        }
        
        return $model->{$attribute}->getKey() !== $relatedModel->getKey();
    }
```

It's a bit more code that I would like it to be, but I think this way `Relatable` supports updating the model if the relation hasn't changed. Any feedback is more than welcome.

**Comment by judge2020** [comment]
Related: https://github.com/laravel/nova-docs/issues/50

**Comment by Jasperrr91** [comment]
First of all, big thanks @kenneth-g-flux for looking into this!

I have tried your fix to Relatable but it does not seem to work for me. I'm going to write some debug code now, to see where stuff goes wrong for me.

**Comment by AdamHutchison** [comment]
+1 for this issue

**Comment by gkermer** [comment]
I'm not able to edit/update the resource, too. When will this issue be fixed?

**Comment by ugurgungezerler** [comment]
+1

**Comment by taylorotwell** [comment]
Fixed in upcoming release.

**Comment by radd2004** [comment]
Can anyone confirm if this should be resolved as of 1.1.8?

**Comment by cjf** [comment]
It is not fixed here.  

Laravel Version: 5.8.3
Nova Version: 2.0.0

**Comment by Landish** [comment]
This issue still exists in:
Nova: 2.12.0
Laravel: 6.18.3

However, on local (valet) it works fine, it has problems only on production deployed with Forge on AWS.

**Comment by amidesfahani** [comment]
this issue still exists in:
nova 3.6

@kenneth-g-flux thanks for your solution.

**Comment by SaundersB** [comment]
FYI. I ran into this issue as well but instead of a Nova bug it was an error on my part.

VIN (HasMany) -> (BelongsTo) Claim (BelongsTo) <- (**HasOne**) Participant

Instead I needed to allow a Participant to have many claims it can be assigned to.

VIN (HasMany) -> (BelongsTo) Claim (BelongsTo) <- (**HasMany**) Participant

This is in regards to some of the previous comments that Laravel will prevent saving a Claim with a duplicate Participant since it's already assigned to another Claim. Hope this helps anybody else who ends up here with the same error and it's not related to the relationshipIsFull solution.

**Comment by xoco70** [comment]
Having this bug in nova 3.7.1 too

**Comment by keizah7** [comment]
I have this problem in  v3.15.0

**Comment by crynobone** [comment]
This issue originated 2 years ago and the original example may no longer relevant. Please create a new issue with reproducing steps if you still have the issue.
