### ISSUE TITLE
Error removing BelongsTo relationship from Resource

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#228]
Nova Version: v1.06

I have a resource which have the following relationship

`
BelongsTo::make('user')->sortable()->searchable(),
`

Even though I remove the value from the searchable dropdown, Nova sends the unselected value as part of the request. This is the data sent by Nova:

`
{
  "id": 99998,
  "code": "XXXXXXXXX",
  "note": null,
  "campaign_id": 1,
  "user_id": 1,
  "created_at": "2018-07-11 14:01:24",
  "updated_at": "2018-08-26 23:52:41",
  "campaign": {
    "id": 1,
    "name": "Test Campaign",
    "created_at": "2018-07-11 17:52:38",
    "updated_at": null,
    "description": ""
  }
}
`

![nova_error](https://user-images.githubusercontent.com/54747/44633567-7bf5f680-a98d-11e8-842c-7eaab2904bab.gif)

It seems like it is related to this:
https://github.com/laravel/nova-issues/issues/120

**Comment by rickmacgillis** [comment]
Same issue here. I need to be able to remove the user or the team from a Laravel Spark invoice using Nova. Only one should be present.

**Comment by RespectPick** [comment]
Same problem. Who know how to fix it?

**Comment by szymon-podeszwa** [comment]
Same problem here.

**Comment by CT-Web** [comment]
It's solved with v1.1.7.
You have to add ->nullable() to the field.

**Comment by DanielProtopopov** [comment]
That does not fix it unfortunately, have checked in Nova 1.1.7 yesterday. Data being passed back from front-end doesn't include the annulated ID, and gets filtered out during assignment.

**Comment by davidhemphill** [comment]
I believe this was solved with the addition of `nullable` in 1.1.7. If you believe there's still an issue. Post a reproducible code example and we'll take a look 😄

**Comment by DanielProtopopov** [comment]
@davidhemphill, I've created Device and User model with device_id, linked them:
User.php:
`	public function device()
	{
		return $this->belongsTo(Device::class);
	}
`

Nova\User.php:
	`public function fields(Request $request) 
{
return [
			ID::make()->sortable(),
`BelongsTo::make('Device')->sortable()->searchable()->nullable()];
}`

Device.php:
`public function users()
	{
		return $this->hasMany(User::class);
	}`

Nova\Device.php:
	`public function fields(Request $request) 
{
return [
			ID::make()->sortable(),
			HasMany::make('Users')->sortable(),
		];
}`

With this I click the X button when editing the User on the Device field, it removes it, and after clicking Update User still has the same Device.
