### ISSUE TITLE
composer update fails on v3.1 due to incorrect requirements

### ISSUE THREAD

**Issue by mattlibera** [laravel/nova-issues#2439]
- Laravel Version: 7.2.*
- Nova Version: 3.1.*
- PHP Version: 7.2.5

### Description:
The `composer.json` for Nova 3.1 is not compatible with Laravel 7 - it looks to have been reverted back since version 3.0.2. It requires `illuminate/support: "^5.7.15 | 5.8.* | ^6.0"` instead of `^7.0`. Thus I cannot install Nova 3.1 with Laravel 7.

### Steps To Reproduce:
* Replace contents of `nova` folder with ZIP contents from v3.1.
* `composer update` on a Laravel 7 app
* version constraints cause the update to fail.

**Comment by crynobone** [comment]
The zip file actually point to `v2.11.0`. I checked `Nova::version()` 

<img width="739" alt="Screenshot 2020-03-18 at 9 44 37 AM" src="https://user-images.githubusercontent.com/172966/76916969-19f93b00-68fd-11ea-9c29-436dc56c084e.png">

**Comment by davidhemphill** [comment]
I tried to replicate your issue by creating a new Laravel application and installing Nova and was able to do so. You might try removing your vendor folder and running `composer update`. Everything looks correct on our end.

**Comment by crynobone** [comment]
@davidhemphill Have you try checking Nova from <https://nova.laravel.com/releases>. The download file does say `nova-3.1.0.zip` but when you check `src/Nova.php` (`version()` method) it says `2.11.1`

**Comment by bashgeek** [comment]
Same issue for me

**Comment by jbrooksuk** [comment]
I have fixed the version available for download.

**Comment by mattlibera** [comment]
thank you @jbrooksuk for the fix and @crynobone for pointing out the actual issue!

**Comment by davidhemphill** [comment]
Sorry all, there was an unresolved issue in our releaser program, but that's been fixed now. Appreciate your patience. 👍

**Comment by Keirul** [comment]
I still have the same issue. 
I looked at the Nova.php file and the version listed there is indeed correct: '3.1.0'.

But if I try to composer update I get the following:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v7.3.0
    - Conclusion: remove laravel/framework v7.2.2
    - Conclusion: don't install laravel/framework v7.2.2
    - Conclusion: don't install laravel/framework v7.2.1
    - Conclusion: don't install laravel/framework v7.2.0
    - Conclusion: don't install laravel/framework v7.1.3
    - Conclusion: don't install laravel/framework v7.1.2
    - Conclusion: don't install laravel/framework v7.1.1
    - Conclusion: don't install laravel/framework v7.1.0
    - Conclusion: don't install laravel/framework v7.0.8
    - Conclusion: don't install laravel/framework v7.0.7
    - Conclusion: don't install laravel/framework v7.0.6
    - Conclusion: don't install laravel/framework v7.0.5
    - Conclusion: don't install laravel/framework v7.0.4
    - Conclusion: don't install laravel/framework v7.0.3
    - Conclusion: don't install laravel/framework v7.0.2
    - Conclusion: don't install laravel/framework v7.0.1
    - Conclusion: don't install laravel/framework v7.0.0
    - laravel/nova 2.x-dev requires illuminate/support ^5.7.15 | 5.8.* | ^6.0 -> satisfiable by laravel/framework[5.7.x-dev, 5.8.x-dev, 6.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.15, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - laravel/nova dev-master requires illuminate/support ^5.7.15 | 5.8.* | ^6.0 -> satisfiable by laravel/framework[5.7.x-dev, 5.8.x-dev, 6.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.15, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[7.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, 6.x-dev].
    - don't install illuminate/support 5.7.17|don't install laravel/framework 7.x-dev
    - don't install illuminate/support 5.7.18|don't install laravel/framework 7.x-dev
    - don't install illuminate/support 5.7.19|don't install laravel/framework 7.x-dev
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.15|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.20|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.21|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.22|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.23|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.26|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.27|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.7.28|don't install laravel/framework 7.x-dev
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.11|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.12|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.14|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.15|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.17|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.18|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.19|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.2|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.20|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.22|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.24|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.27|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.28|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.29|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.3|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.30|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.31|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.32|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.33|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.34|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.35|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.36|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.4|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.8|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v5.8.9|don't install laravel/framework 7.x-dev
    - don't install illuminate/support 6.x-dev|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.0.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.0.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.0.2|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.0.3|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.0.4|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.1.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.10.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.11.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.12.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.13.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.13.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.14.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.15.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.15.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.16.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.17.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.17.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.18.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.18.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.18.2|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.2.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.3.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.4.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.5.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.5.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.5.2|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.6.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.6.1|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.6.2|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.7.0|don't install laravel/framework 7.x-dev
    - don't install illuminate/support v6.8.0|don't install laravel/framework 7.x-dev
    - Installation request for laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2, v7.3.0].
    - Installation request for laravel/nova * -> satisfiable by laravel/nova[2.x-dev, dev-master].`

**Comment by andrewwindfall** [comment]
I have the same issue as Keirul, any word on that?

**Comment by crynobone** [comment]
@Keirul please create a new issue.
