### ISSUE TITLE
Currency field throws exception on create/edit view when used with asMinorUnits

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#2623]
- Laravel Version: 7.11
- Nova Version: 3.6.0
- PHP Version: 7.4

### Description:

The `Currency` field throws an exception on the create/edit view when it's being used with the `asMinorUnits()` method. Example usage:

```php
Currency::make('Balance')
    ->rules('integer')
    ->asMinorUnits(),
```

When vising the edit or create view of the resource, the following exception will be thrown:

```
The given value "" does not represent a valid number.
```

**Comment by SquareBeard** [comment]
And it does throw the same exception without using `asMinorUnits` on the detail view if the value is null.

The Currency field doesn't work well with null values.

**Comment by dkulyk** [comment]
You should set default value as 0 for field.
```
protected $attributes = [
    'balance' => 0
];
```

**Comment by chescos** [comment]
Issue still exists

**Comment by chescos** [comment]
@taylorotwell @davidhemphill @jbrooksuk This "stale" bot only makes sense if you would address bugs within the timeframe that the bot marks an issue as stale. Why would you force continued activity on an issue without the maintainers responding to the bug?

**Comment by crynobone** [comment]
Fixed in `v3.12.0` via laravel/nova#991

**Comment by SquareBeard** [comment]
The fix was reverted.
It is still throwing an exception on the detail view if the value is null.

**Comment by crynobone** [comment]
@SquareBeard thank you for the report.

Yes there been some missing changes during the initial PR causing it to be reverted before `v3.12.0` release. Send a new PR laravel/nova#1008

**Comment by neilhamilton** [comment]
This appears to still be a problem in `3.19.0`

It looks like no matter what, when saving a model and minor units are being used, it's trying to convert the value using `toMoneyInsance`.

When I override the construct in my own `App\Nova\Fields\Currency` file, and change the following lines, it works ok:

```
            if ($this->minorUnits) {
                $model->$attribute = $this->toMoneyInstance($value)->getMinorAmount()->toInt();
            } else {
                $model->$attribute = $value;
            }
```

becomes

```
            if ($this->minorUnits) {
                $model->$attribute = !$this->isNullValue($value) ? $this->toMoneyInstance($value)->getMinorAmount()->toInt() : null;
            } else {
                $model->$attribute = $value;
            }
```

**Comment by crynobone** [comment]
@neilhamilton please create a new issue explaining your issue. Above issue has been fixed and we would like to review and verify each issue individually.
