### ISSUE TITLE
Action events are availabe through global search & resources/action-events

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2635]
Laravel Version: 7.11.0
Nova Version: 3.6.0
PHP Version: 7.2.19
Database Driver & Version: mysqlm 5.7.24
Operating System and Version: windows 10
Browser type and version: chrome 81 (64 bits)

### Description:

I'm not using action events, but they are still registered for every change on a resource. My issue is that i can find action events while searching for a number (which can be the same as an action event id).

### Steps To Reproduce:

- Fresh nova installation
- Do not use Laravel\Nova\Actions\Actionable trait anywhere
- Set withoutActionEvents to false on all actions
- Change a resource
- Check action_events table and observe a new entry

### Question

- How can i disable access to action events in the global search?
- How can i remove the index page route for action events?
- Bonus: How can i remove creating the action events?

**Comment by preliot** [comment]
@jelib3an Your solution works! Thanks!

**Comment by AbetaNL** [comment]
This solution works very well to remove the actions from the global search, but they are still available if you know the URL.
(E.G.  http://127.0.0.1:8000/nova/resources/action-events/2 ) 

Is there any way to make the action events only visible to users with a certain level? I understand this is not the same problem as the original question, but I think it is a logical follow up given the security issue that (I assume) OP tried to solve.

**Comment by jelib3an** [comment]
Good point. I haven't tested this, but I assume one can create a policy for it just like any other resource.

`php artisan make:policy --model="\Laravel\Nova\Actions\ActionEvent" ActionEventPolicy`

Then register it in AuthServiceProvider:
`protected $policies = [
        'Laravel\Nova\Actions\ActionEvent' => 'App\Policies\ActionEventPolicy',
];`

**Comment by AbetaNL** [comment]
@jelib3an Thank you very much, that works nicely indeed! 
btw, in your 1st reply you accidentally typed \Larave instead of \Larave**l**  (You forgot the l)

**Comment by jelib3an** [comment]
Haha, thanks! Typo is fixed now.

**Comment by Lednerb** [comment]
This issue is still a thing one year later - maybe this issue should be opened again so it can be fixed for all users and also in newer versions.

Actual version affected: 3.25.0

The global fix would be to adjust the `ActionResource`:
https://laracasts.com/discuss/channels/nova/how-can-i-disable-actions-in-global-search-in-laravel-nova?page=1#reply=623309
