### ISSUE TITLE
Select field  - Do not set the selected option if the key is 0

### ISSUE THREAD

**Issue by kazunn** [laravel/nova-issues#278]
If we define a select field as follows 

 Select::make('User Level')->options([
                0 => 'Blocked',
                1 => 'Pending',
                2 => 'Verified',
            ])

if the current value of is 0, then the 'Blocked' option is not selected as the edit window loading. 
It is not the case with 1 and 2 (Pending and Verified ) where those are selected by default correctly as loading the edit window.

**Comment by DenzoNL** [comment]
Can confirm, having the exact same issue on Nova 1.0.6

**Comment by ovvessem** [comment]
Can confirm for Nova 1.0.8

**Comment by ErwanGuillon** [comment]
Same here 1.0.7

**Comment by macolson** [comment]
Can confirm for Nova 1.0.14

**Comment by davidhemphill** [comment]
Fixed in laravel/nova-js#4

**Comment by fourstacks** [comment]
Hi @davidhemphill - it looks like this issue is still present in v1.1.7.  I have a more or less identical select field config to the OP and if the field has a value of `0` then then option for that value is not preselected in the select field on the edit view.

This looks to be related to several other issues: #562 #840 #500 #122 #951

**Comment by newtongamajr** [comment]
Problem still happening on Laravel Nova 2.9.2

**Comment by mrtawil** [comment]
A fix would be as follows using `resolveUsing`:

```
Select::make('Response')
  ->options([
      0 => 'No',
      1 => 'Yes',
  ])
  ->resolveUsing(function () {
      if ($this->response === 0) {
          return '0';
      }
  })
```

> The resolveUsing method allows you to customize how a field is formatted after it is retrieved from your database but before it is sent to the Nova front-end. This method accepts a callback which receives the raw value of the underlying database column

https://nova.laravel.com/docs/4.0/resources/fields.html#field-resolution-formatting

**Comment by hashs42** [comment]
Can confirm for Nova 4.22.2
