### ISSUE TITLE
Upgrade to Nova 4: registerStoreModules() undefined reading forEach

### ISSUE THREAD

**Issue by cwray-tech** [laravel/nova-issues#3827]
- Laravel Version: ^9.2
- Nova Version: ~4.0
- PHP Version: 8.1.2
- Database Driver & Version:  PostgresSQL vs 14.2
- Operating System and Version: Laragon Windows 11
- Browser type and version: Google chrome, Microsoft Edge, latest versions
- Reproduction Repository: NA Private 

### Description:
Working on upgrading a Laravel project to Nova 4 today. I have removed all third party Nova packages and ensured that they are not being loaded. I also followed the nova upgrade guide, but now I am running into an issue that I can't see what the cause is. When visiting the nova admin panel, nothing is displayed on the screen, but in the console I am seeing the following error:
#### Console Error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at ir.registerStoreModules (app.js:326:17)
    at ir.liftOff (app.js:167:10)
    at login:42:14
registerStoreModules @ app.js:326
liftOff @ app.js:167
(anonymous) @ login:42
```
This looks like this is related to the resources not being loaded, as when I inspect the place where the error is throwing, it is looping through the resources and registering the Vuex modules for each one:
```javascript
/**
   * Register the built-in Vuex modules for each resource
   */
  registerStoreModules() {
    this.config('resources').forEach(resource => { // Error is being thrown at this line.
      this.store.registerModule(resource.uriKey, resourceStore)
    })

    this.app.use(this.store)
  }
```

Maybe I have missed something that is simple, so I wanted to submit this here, and if not it may be a bug.

We were on the latest version of Nova 3 before trying the upgrade.

#### Here is my composer.json:
```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "ext-json": "*",
        "cwray-tech/saml2": "master",
        "dyrynda/laravel-cascade-soft-deletes": "^4.2",
        "guzzlehttp/guzzle": "^7.4.2",
        "laravel/framework": "^9.2",
        "laravel/helpers": "^1.5",
        "laravel/nova": "~4.0",
        "laravel/sanctum": "^2.15",
        "laravel/tinker": "^2.7",
        "maatwebsite/excel": "^3.1",
        "magnetco/tvonmyside": "*",
        "mews/purifier": "3.3.7",
        "mobiledetect/mobiledetectlib": "^2.8",
        "phattarachai/laravel-mobile-detect": "^1.0",
        "predis/predis": "^1.1",
        "spatie/eloquent-sortable": "^4.0",
        "spatie/laravel-medialibrary": "^10.3.1",
        "spatie/laravel-permission": "^5.5",
        "spatie/laravel-sluggable": "^3.4"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "fakerphp/faker": "^1.9.1",
        "laravel/breeze": "^1.9",
        "laravel/sail": "^1.13.8",
        "mockery/mockery": "^1.5",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cwray-tech/Saml2.git"
        },
        {
            "type": "composer",
            "url": "https://nova.laravel.com"
        },
        {
            "type": "path",
            "url": "./nova-components/Tvonmyside"
        }
    ],
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan nova:publish"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "phpstan/extension-installer": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

This is an example of my auth.json with license key removed:
```json
{
    "http-basic": {
        "nova.laravel.com": {
            "username": "our email to our account",
            "password": "our license key"
        }
    },
}
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
This is not happening on a fresh install. 
1. Create laravel 9 app with latest version of nova 3.0 added in the repository. (Not installed via composer)
2. Upgrade to nova 4.0 as a composer dependency (add auth.json, and update respository key in composer.json)
3. Update composer packages as needed.
4. Update the path of the  nova admin panel to /tv/admin (We are using wildcard routes, so we needed to nest the admin panel in another url)
5. visit the admin panel.

**Comment by crynobone** [comment]
Have you followed the upgrade guide: https://nova.laravel.com/docs/4.0/upgrade.html#updating-configuration-assets-and-translations

The suggested line indicates that `Nova.config('resources')` doesn't contain an `array` and that only possible if you upgrade to Nova 4 without removing `resources/views/vendor/nova/layout.blade.php` as suggested in the Upgrade Guide.

**Comment by cwray-tech** [comment]
Hmm yes I did do that and follow the upgrade guide. I will recheck in a bit.

**Comment by cwray-tech** [comment]
@crynobone yeah, I double checked that and I did do that. Also re run those commands and tried removing everything from the nova published views.

I also noticed that in the data-page attribute, the json doesn't look like it is properly formatted? Below is a screenshot of the devtools inspection and this is what it is:
```
  data-page="{&quot;component&quot;:&quot;Nova.Error&quot;,&quot;props&quot;:{&quot;errors&quot;:{},&quot;novaConfig&quot;:[],&quot;currentUser&quot;:null,&quot;validLicense&quot;:false},&quot;url&quot;:&quot;\/tv\/admin\/login&quot;,&quot;version&quot;:&quot;nova::layout:0f4e2ee0f7e2ca9da665d2f8035743df&quot;}"
```
![scrnli_4_5_2022_8-34-12 PM](https://user-images.githubusercontent.com/53663762/161890938-beee76d0-5913-47b8-800e-656f4ee9a9f7.png)

**Comment by cwray-tech** [comment]
@crynobone yeah that is the issue. Something is causing the inertia data to be malformed in the app.

**Comment by crynobone** [comment]
@cwray-tech submit reproducing code such as https://github.com/nova-issues

**Comment by cwray-tech** [comment]
@crynobone 
<a href="https://www.loom.com/share/e71a0de7eec04731b496be5ae3dfaae0">
    <p>Upgrade Guide | Laravel Nova - 6 April 2022 - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e71a0de7eec04731b496be5ae3dfaae0-with-play.gif">
  </a>
Sorry my baby can be heard in the background.

I will try to upload an example repo if @pramanikriju is unable.
Thanks

**Comment by pramanikriju** [comment]
> @crynobone [ ](https://www.loom.com/share/e71a0de7eec04731b496be5ae3dfaae0)
> 
> [Upgrade Guide | Laravel Nova - 6 April 2022 - Watch Video](https://www.loom.com/share/e71a0de7eec04731b496be5ae3dfaae0)
> 
> [ ![](https://camo.githubusercontent.com/117b783ce61773ce197e2bc8e0e7a3c7616ad97f14f0a0f108bccd81cb987634/68747470733a2f2f63646e2e6c6f6f6d2e636f6d2f73657373696f6e732f7468756d626e61696c732f65373161306465376565633034373331623439366265356165336466616165302d776974682d706c61792e676966) ](https://www.loom.com/share/e71a0de7eec04731b496be5ae3dfaae0)
> Sorry my baby can be heard in the background.
> I will try to upload an example repo if @pramanikriju is unable. Thanks

You can go ahead with the repo. I was unable to replicate this on a fresh install. 

As a side note - I was able to fix my issue by following the laravel.log file and fixing the errors in that one by one.

**Comment by arrgh11** [comment]
I'm running into the same issue as @cwray-tech. Here's my output from the above command @crynobone : 
```
ajaxray/php-watermark      v0.1.1  Add text or image watermark on images.
blade-ui-kit/blade-icons   1.2.2   A package to easily make use of icons in your Laravel Blade views.
blade-ui-kit/blade-ui-kit  0.3.3   A set of renderless components to utilise in your Laravel Blade views.
fakerphp/faker             v1.19.0 Faker is a PHP library that generates fake data for you.
fruitcake/laravel-cors     v2.2.0  Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
guzzlehttp/guzzle          7.4.2   Guzzle is a PHP HTTP client library
hisorange/browser-detect   4.4.1   Browser & Mobile detection package for Laravel.
laravel/framework          v9.7.0  The Laravel Framework.
laravel/jetstream          v2.7.2  Tailwind scaffolding for the Laravel framework.
laravel/nova               4.0.3   A wonderful administration interface for Laravel.
laravel/sail               v1.13.9 Docker files for running a basic Laravel application.
laravel/sanctum            v2.15.0 Laravel Sanctum provides a featherweight authentication system for SPAs and simple APIs.
laravel/tinker             v2.7.2  Powerful REPL for the Laravel framework.
laravel/vapor-core         v2.21.3 The kernel and invokation handlers for Laravel Vapor
league/flysystem-aws-s3-v3 3.0.13  AWS S3 filesystem adapter for Flysystem.
livewire/livewire          v2.10.4 A front-end framework for Laravel.
mockery/mockery            1.5.0   Mockery is a simple yet flexible PHP mock object framework
mpdf/mpdf                  v8.0.17 PHP library generating PDF files from UTF-8 encoded HTML
nunomaduro/collision       v6.2.0  Cli error handling for console/command-line PHP applications.
org_heigl/ghostscript      2.3.2   A PHP-Wrapper around the Ghostscript-CLI
phpunit/phpunit            9.5.20  The PHP Unit Testing framework.
rbdwllr/reallysimplejwt    4.0.3   A really simple library to generate user authentication JSON Web Tokens.
sentry/sentry-laravel      2.12.0  Laravel SDK for Sentry (https://sentry.io)
spatie/laravel-ignition    1.2.0   A beautiful error page for Laravel applications.
```

**Comment by arrgh11** [comment]
@cwray-tech Looks like my issue was a policy mismatch. @pramanikriju was right, gotta look at the Laravel log and find the errors there...

My issue is that I'm installing it into an existing app that had tons of existing packages that I had to remove in order to install Nova 4.

**Comment by cwray-tech** [comment]
@pramanikriju This is related to the Request type on the resource methods. I updated the methods to accept the Illuminate\Http\Request class, and the issue was solved. Upgrade guide should probably be edited.

**Comment by pramanikriju** [comment]
> @pramanikriju This is related to the Request type on the resource methods. I updated the methods to accept the Illuminate\Http\Request class, and the issue was solved. Upgrade guide should probably be edited.

That is odd because I updated all my Requests to `NovaRequest $request` and that fixed the issue for me. 
Could you confirm your Nova version @cwray-tech ?

**Comment by cwray-tech** [comment]
4.0.4

**Comment by cwray-tech** [comment]
@pramanikriju I only updated the fields, cards and actions methods. Index queries still accept the NovaRequest.

**Comment by pramanikriju** [comment]
You could tail your logs and paste the last error that you receive

**Comment by cwray-tech** [comment]
@pramanikriju The errors were all related to the Request param.
```
[2022-04-06 15:00:51] local.ERROR: Could not check compatibility between App\Nova\Content::actions(App\Nova\Request $request) and Laravel\Nova\Resource::actions(Laravel\Nova\Http\Requests\NovaRequest $request), because class App\Nova\Request is not available {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Could not check compatibility between App\\Nova\\Content::actions(App\\Nova\\Request $request) and Laravel\\Nova\\Resource::actions(Laravel\\Nova\\Http\\Requests\\NovaRequest $request), because class App\\Nova\\Request is not available at C:\\laragon\\www\
ctc-disputes\\app\\Nova\\Content.php:256)
[stacktrace]
#0 {main}
"}
```

**Comment by pramanikriju** [comment]
`App\Nova\Content::actions(App\Nova\Request $request)`  @ app\Nova\Content.php:256
Try changing this to `NovaRequest $request` @cwray-tech

**Comment by cwray-tech** [comment]
@pramanikriju That was what it was when the error was being thrown. I changed it to Request, and the issue was solved.

**Comment by cwray-tech** [comment]
@crynobone this shouldn't have been closed. This issue needs to be fixed, either in the documentation for the upgrade guide, or the underlying cause of not working with a NovaRequest parameter as stated is the case in the upgrade guide.

**Comment by crynobone** [comment]
@cwray-tech you have to provide a way for us to debug the actually issue, can you submit a reproducing repository? Otherwise we have to consider this as usage issue.

A bug is something that can be reproduced, a reproducing repository can confirmed it.

**Comment by cwray-tech** [comment]
@crynobone I absolutely can! The thing is that I have major deadlines that I need to meet for my clients and, no I cannot do it in less than 24 hours. 

This issue does not seem to be only related to my usage, or else the discord would not be full of others having the exact same issue. 

This is, one, an issue with the upgrade guide or, two, an issue in the code base, which is related to upgrading from an older version of Nova to a newer version of Nova. 

Please have patience with me and I can submit a repo with the issue replicated. I thought another commenter was going to do that, so I held off.. if they aren't, I can try to have a replicating issue by no earlier than Saturday.

**Comment by crynobone** [comment]
No, they have different problem compared to you, some already has been addressed and PRed. I have no idea what wrong on your case and there no way for me to reproduce it. The video you shown just proved that you don't have the correct combination. 

Nova 4 uses `NovaRequest` as mentioned on the documentation. Nova 3 uses `Request`. Submit reproducing repository is the only way forward.

**Comment by StanBarrows** [comment]
@crynobone 

I've had a similar issue. Can you try removing all old Resources from your repository? I've moved them into a different folder but still received the above error.
