### ISSUE TITLE
Filters not working well with special characters

### ISSUE THREAD

**Issue by neamtua** [laravel/nova-issues#392]
Hello,

I've found an issue using filters that contain special utf-8 characters. It appears it cannot filter entries correctly or at all.

Here's an example of what i'm saying.
<img width="1395" alt="screen shot 2018-09-02 at 12 48 34" src="https://user-images.githubusercontent.com/1029457/44954693-b7715300-aeae-11e8-9f30-7cf5f29e3e7b.png">
The above image shows all my entries. Check the values on the Institution column.

<img width="1409" alt="screen shot 2018-09-02 at 12 48 49" src="https://user-images.githubusercontent.com/1029457/44954699-c952f600-aeae-11e8-89a0-f1368cb299b2.png">
The above image shows filtering by a simple name with no special characters. Everything works as expected.

<img width="1401" alt="screen shot 2018-09-02 at 12 49 02" src="https://user-images.githubusercontent.com/1029457/44954703-da036c00-aeae-11e8-82f4-e03a2c7ac12c.png">
Here is the filtering after a value that has special characters. It just shows all the values, even the null ones.

Here is my filter code:

```php
public function apply(Request $request, $query, $value)
{
	return $query->where('institution', $value);
}
public function options(Request $request)
{
	return config('members');
}
```

Here are the values in my config:

```php
return [
	'Universität Ulm' => 'Universität Ulm',
    'Universidade Nova de Lisboa' => 'Universidade Nova de Lisboa',
    'Maastricht University' => 'Maastricht University',
    'Linköpings Universitet' => 'Linköpings Universitet',
];
```

All entries with special characters filter incorrectly.
I've checked database charset and database connection charset. Everything is utf8mb4.

Thank you.

**Comment by neamtua** [comment]
Still same behaviour on 1.0.9.

**Comment by AegirLeet** [comment]
This is an encoding issue. The filter values need to be encoded in UTF-8 (in JS), otherwise json_decode will fail (in PHP).
In resources/js/store/resources.js, modify the currentFilters getter to use something like `value: utf8.encode(f.currentValue)` instead of a simple `value: f.currentValue,` (using https://www.npmjs.com/package/utf8).

**Comment by christophrumpel** [comment]
@neamtua depending on how many different possible values, you can also use quick-fix solution by querying for both versions of the word. In my case this looks like this:

```
public function apply(Request $request, $query, $value)
{
    return $query->where('brand', $value)->orWhere('brand', str_replace('oe', 'ö', $value));
}
```

Not the best solution, but probably better than start dealing with encoding in Nova itself.

**Comment by davidhemphill** [comment]
This should now be fixed.

**Comment by kamilkozak** [comment]
It still does not work. Do not search when the word contains the Polish character "ę"

**Comment by jbrooksuk** [comment]
@kamilkozak could you please open a new issue, as this issue related to v1 of Nova, thanks!
