### ISSUE TITLE
Clicking on Dashboards cause scrolling locked incorrectly

### ISSUE THREAD

**Issue by vitaliy-gituser** [laravel/nova-issues#4281]
- Laravel Version: 9.13.0
- Nova Version: 4.6.1
- PHP Version: 8.1.4
- Database Driver & Version: 
- Operating System and Version: Ubuntu 18.04.5 LTS
- Browser type and version: Google Chrome.100.0.4896.88

### Description:
Sometimes the scroll does not turn on, and in order to turn it on or off again, it’s needed to click on the navigation menu again.

### Detailed steps to reproduce the issue on a fresh Nova installation:

https://user-images.githubusercontent.com/73833107/169258129-0f9422f2-ed3a-4621-82d4-6e7f2150b204.mp4

**Comment by crynobone** [comment]
Please ensure you have the latest asset by running `php artisan nova:publish`

**Comment by vitaliy-gituser** [comment]
Of course this command was executed and cache was cleared and the issue still persists

**Comment by vitaliy-gituser** [comment]
> Please ensure you have the latest asset by running `php artisan nova:publish`
Of course this command was executed and cache was cleared and the issue still persists

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/169265526-da31e46d-0b4c-483a-a810-c2c21f59c427.mp4

Not able to reproduce the issue. please submit reproducing repository similar to https://github.com/nova-issues in order for us to debug the issue further.

**Comment by vitaliy-gituser** [comment]
> 

I will tell you how to reproduce the issue I encountered. Do so that in Dashboards there was only one Dashboard menu. I.e. so that navigation was not a dropdown list and if you click again on this menu the scroll appears and disappears. I also checked it on mac OS in Chromium browser. It worked the same way for me as in your video.

**Comment by vitaliy-gituser** [comment]
> CleanShot.2022-05-19.at.17.48.52.mp4 
> Not able to reproduce the issue. please submit reproducing repository similar to https://github.com/nova-issues in order for us to debug the issue further.

**Comment by jaxramus** [comment]
I am using 4.6.1 now, scrollbar issues still happening.

related: https://github.com/laravel/nova-issues/issues/4271

**Comment by ianrobertsFF** [comment]
@crynobone `MenuSection.vue` is missing the new `mainMenuShown` getters present in MenuItem.vue

**Comment by jaxramus** [comment]
@davidhemphill  this issue still exists even with 4.6.1 and having published the nova assets.

**Comment by davidhemphill** [comment]
I merged a PR addressing this issue which autoclosed this.

**Comment by osama-klabs** [comment]
@davidhemphill this issue still exists in laravel nova 4.7.0
same like @vitaliy-gituser video
i already try php artisan nova:publish --force
