### ISSUE TITLE
[Bug] MorphTo not working on form edit when there is a morphmap assigned

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/nova-issues#430]
I have a MorphMap assigned in my AppServiceProvider like so:

```
Relation::morphMap([
    'campaign' => Campaign::class,
    'campaign_offer' => CampaignOffer::class,
]);
```

In my resource class, I defined the MorphTo field (with columns named related_id, related_type) like so:

```
MorphTo::make('Related')->types([
    Campaign::class,
    CampaignOffer::class,
])->searchable(),
```

On the index and the detail page, all is good! We can see the related campaign and campaign offers. But on the form page, when I click edit on a record, the values are not pre-populated properly. Here are the screenshots:

Index Page looking good:

<img width="1132" alt="screen shot 2018-09-04 at 10 01 08 pm" src="https://user-images.githubusercontent.com/16099046/45044722-8f404a80-b08e-11e8-8745-69bedd288a84.png">

Form Detail looking good:

<img width="1146" alt="screen shot 2018-09-04 at 10 03 56 pm" src="https://user-images.githubusercontent.com/16099046/45044759-a54e0b00-b08e-11e8-923d-f1fc51eff37b.png">

Form edit broken (this is for ID 421 as shown in the screenshots above) ! The expected behaviour is that it should have the associated Campaign Offer populated on the edit page

<img width="1136" alt="screen shot 2018-09-04 at 10 04 06 pm" src="https://user-images.githubusercontent.com/16099046/45044775-b1d26380-b08e-11e8-966a-734b7e62a92a.png">

**Comment by paras-malhotra** [comment]
@taylorotwell @themsaid would appreciate if you guys could look into this. Thanks

**Comment by mikebouwmans** [comment]
I'm experiencing the exact same issue, even putting it in NovaServiceProvider is not working.

**Comment by 907544030** [comment]
+1

**Comment by davidhemphill** [comment]
Believe this was fixed in 1.1.2.

**Comment by paras-malhotra** [comment]
@davidhemphill I've updated to Nova 1.1.3 but it **isn't fixed** yet. The same issue occurs. I have run the commands `php artisan nova:publish` and `php artisan view:clear`

**Comment by paras-malhotra** [comment]
@davidhemphill can you please reopen this issue? The problem still persists.

**Comment by paras-malhotra** [comment]
Opened a new issue because this has not been resolved yet and closed without resolution. Refer #744
