### ISSUE TITLE
delete notification confirm dialog is not localized

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#4432]
- Nova Version: 4.9.0

### Description:
The confirm dialog "Are you sure you want to delete this notification?" is not translatable.

Also it would be nice, if the message part of a nova notification would allow html, e.g. to add line-breaks or bold text.

**Comment by robbedekien** [comment]
Just jumping in, it is translatable. Add this key to your translation file if it is missing `Are you sure you want to delete this notification?`

**Comment by m-lotze** [comment]
Missed that. Thanks.

**Comment by robbedekien** [comment]
Ok apparently we have extended the notification ourselves with the exact snippet you suggested so you are right. I just started assuming it was supported out of the box. Sorry!

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by m-lotze** [comment]
@davidhemphill 

You missed the `this.` before `__`. This now produces a `ReferenceError: __ is not defined` and no confirm dialog shows up.

**Comment by davidhemphill** [comment]
Oops! Just released a fix for this.
