### ISSUE TITLE
[1.0.8] PostgreSQL - Searching on non-text column types returns an error

### ISSUE THREAD

**Issue by reganjohnson** [laravel/nova-issues#46]
When you are including numeric values (such as model ID), or other non-text / string equivalent column types as part of the searchable fields array, the resulting search query is not valid for PostgreSQL databases (when searching using a non-integer string).

PostgreSQL is expecting pattern matching to use a string. Thus, when using `like` on columns that are numeric (or other non-text types), you must first cast the column values using `::text`.

Further, it would be advisable to use `ilike` instead of `like` as PostgreSQL is case sensitive.

The error I am getting is:
```
Undefined function: 7 ERROR: operator does not exist: integer ~~ unknown LINE 1:
select * from "products" where ("products"."id" like '%Term%') ...
```

Which should be re-written to something similar to:
```
select * from "products" where ("products"."id"::text ilike '%Term%') ...
```

Edit: Correct version, and expand definition outside of numeric column types.

**Comment by Gnative** [comment]
I can confirm this, wasn't sure if it was just related to Postgres as I haven't installed Nova on a MySQL base yet.
Currently removed 'id' from the $search array until a fix was supplied..

**Comment by MattMangoni** [comment]
+1

**Comment by BengtHagemeister** [comment]
+1

**Comment by SethTompkins** [comment]
+1

**Comment by reganjohnson** [comment]
You are correct, @chescos - I updated the ticket title and description to bette reflect. Hopefully they get this ticket looked at soon - it's pretty important.

**Comment by hotmeteor** [comment]
I also have a possible solution where the model's key is filtered from the text-searched columns:

`Laravel\Nova\PerformsQueries@applySearch`:
```php
protected static function applySearch($query, $search)
{
    if (is_numeric($search) && in_array($query->getModel()->getKeyType(), ['int', 'integer'], true)) {
        $query->whereKey($search);
    }

    return $query->where(function ($query) use ($search) {
        $model = $query->getModel();

        foreach (static::searchableColumns() as $column) {
            if ($column !== $query->getModel()->getKeyName()) {
                $query->orWhere($model->qualifyColumn($column), 'like', '%'.$search.'%');
            }
        }
    });
}
```

Not sure if this is a flexible enough solution though.

**Comment by chescos** [comment]
Could someone from the Nova team let us know if this issue has a high priority and if there an ETA for a fix? I really like Nova so far and I would like to use it for production but this issue makes it impossible because being able to search for model IDs is crucial.

**Comment by LeonAlvarez** [comment]
any news?

**Comment by itenerant** [comment]
<img width="1036" alt="screen shot 2018-09-10 at 5 02 24 pm" src="https://user-images.githubusercontent.com/2393282/45302279-87aff400-b51b-11e8-8a34-a54562eb645a.png">
+1

**Comment by davidhemphill** [comment]
There was an issue fixed in 1.0.15 related to allow numeric searches to search on fields other than the primary key. Can anyone confirm if this solves your issue?

**Comment by SethTompkins** [comment]
@davidhemphill it did not, still getting the same error when entering '1' in the search bar.

**Comment by chescos** [comment]
@davidhemphill it's still the same exception that is getting thrown:

```
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer ~~ unknown
```

Here is an example SQL query the causes the exception:

```
SELECT *
FROM "users"
WHERE ("users"."id" LIKE %test%
       OR "users"."name" LIKE %test%
       OR "users"."email" LIKE %test%)
ORDER BY "users"."id" DESC
LIMIT 26
OFFSET 0
```
The issue here is that the `"users"."id"` column is of the type `integer`. PostgreSQL doesn't seem to support the `LIKE` operator on non-text types (I experienced this exception with `integer` and `inet` types but there are probably many more that don't work with `LIKE`).

You can reproduce this error by using PostgreSQL as a database driver and adding any column of the type `integer` to the `$search` property on a resource. Then try to perform a search on this resource.

**Comment by m-bymike** [comment]
+1

**Comment by m-bymike** [comment]
This is something that can get fixed by the Laravel framework, see pull request above.

**Comment by m-bymike** [comment]
The pull request targets Laravel 5.7, but since Nova works with Laravel 5.6 too, would it make sense to fix it in 5.6 too?

**Comment by chescos** [comment]
@m-bymike thanks for your effort implementing this fix!

As someone who purchased the Nova license, I would expect this bug to be fixed for Laravel 5.6 too. This isn't a minor issue. It makes Nova itself mostly unusable with PostgreSQL because it breaks both the global and the local search.

If the fix isn't merged into Laravel 5.6 as well, I think there should be a note/warning that Nova only works with 5.7+ when using PostgreSQL.

**Comment by m-bymike** [comment]
I'll try to get the fix into 5.6, keep you posted.

**Comment by taylorotwell** [comment]
Fixed in upcoming Laravel 5.7 release. 5.6 is closed to security fixes only. But, the upgrade from 5.6 to 5.7 is quite easy.

**Comment by chescos** [comment]
@davidhemphill @taylorotwell There's a new bug that's related to this issue, see #680

**Comment by RobvH** [comment]
+1 for fixing it
-1 for not back porting the fix to 5.6
