### ISSUE TITLE
Nova v1.0.13: problem with nova-assets

### ISSUE THREAD

**Issue by abordage** [laravel/nova-issues#482]
Styles not work: 
![nova13](https://user-images.githubusercontent.com/28537731/45247764-c9218300-b312-11e8-9728-da531bdfb19a.png)

**Comment by antoniolore** [comment]
Same thing happened to me... after the update I got the same errors in console. Reverted to 1.0.12

**Comment by glennwilton** [comment]
The same issue here, this.CreateNova is undefined and can not set the global Nova object, causing all the vues to fail.

Reverted to 1.0.12

**Comment by nnerijuss** [comment]
I have this problem too.

**Comment by Jam0r85** [comment]
Can't roll back to 1.0.12, still have the same issue.

I used nova:publish when updating.

**Comment by paras-malhotra** [comment]
+1

**Comment by daguilarm** [comment]
Same problem

**Comment by petericebear** [comment]
Same issue here, Trying to locate the issue

**Comment by cloudstudio** [comment]
@themsaid @davidhemphill can you check it guys ? all break

**Comment by fwartner** [comment]
Same for me.

**Comment by hocza** [comment]
Same :(

**Comment by ryryan** [comment]
Same for me. Rolled back to 1.0.12 and it worked fine.

**Comment by loren138** [comment]
Glad I made a specific commit for the upgrade. `git revert` time....

**Comment by rickmacgillis** [comment]
@taylorotwell and team, the way to reproduce this error is to do the following:

1. Install a brand new Laravel 5.7 installation.
2. Install Nova. (`php artisan nova:install` and `php artisan nova:publish`)
3. Create a user.
4. Log into Nova.
5. See the error.

This error is NOT reproducible when upgrading from Nova 1.0.12 for some reason. Once I replaced the `nova-assets` directory with a working copy, the test site worked. Once I deleted the `nova-assets` directory and re-published the Nova assets, it still works, even with a cleared browser cache.

POSSIBLE FIX (May be why it still works after republishing):

1. `cd` to the laravel/nova vendor directory.
2. `npm install`
3. `npm run dev`
4. Delete the `public/nova-assets` directory.
5. `php artisan:publish`

**Comment by ilvalerione** [comment]
This 5 steps solve the problem but before start you need to rename `webpack.mix.js.dist` to `webpack.mix.js` to run `npm run dev` without issues.

**Comment by Jam0r85** [comment]
When doing the above I get the following error..

```
 error  in ./resources/js/components/Icons/Loader.vue

Syntax Error: Unexpected token (18:12)

  16 |     render(h) {
  17 |         return (
> 18 |             <svg
     |             ^
  19 |                 class="mx-auto block"
  20 |                 style={{ width: `${this.width}px` }}
  21 |                 viewBox="0 0 120 30"
```

**Comment by Josh865** [comment]
I'm experiencing the same issue after adding Nova to a fresh Laravel 5.7 installation.

**Comment by clarkewing** [comment]
Experienced this issue upgrading from v1.0.4

**Comment by mobeelco** [comment]
@rickmacgillis 
worked for me
Thank's

**Comment by noahlocke** [comment]
@rickmacgillis worked for me also, but I think you meant `php artisan vendor:publish` right?

**Comment by rickmacgillis** [comment]
@noahlocke `nova:publish`

**Comment by Goldfinch** [comment]
@rickmacgillis thanks for discovering this, it saved my time, also in addition to @ilvalerione comment, I noticed that **nova-app** folder is creating in the root during **npm run** because of this

`.copy('public', '../nova-app/public/nova')`

I think this is excess and can be removed to keep it clear until an official fix

**Comment by paras-malhotra** [comment]
@rickmacgillis the error also occurs on upgrading from Nova v1.0.12

**Comment by edh72** [comment]
Same issue here - Nova v1.0.8  --> v1.0.13 update

**Comment by rivenme** [comment]
Same here, Update from 0.8 to 0.13

**Comment by pragmaniac** [comment]
Same issue, brand new Laravel 5.7 install including Nova and the same errors in console. Tried renaming webpack.mix.js.dist to webpack.mix.js and did a fresh npm install in the Nova directory to no avail.

**Comment by bluec** [comment]
Just to tidy up @rickmacgillis fix (confirmed working here):

1. change to the `vendor/laravel/nova` directory
1. rename `webpack.mix.js.dist` to `webpack.mix.js`
1. run `npm install`
1. run `npm run dev`
1. change back to the project root directory and delete the `public/nova-assets` directory.
1. run `php artisan nova:publish`

**Comment by bluec** [comment]
Confirmed fixed for me in 1.0.14

**Comment by DonDiegoAA** [comment]
Release 1.0.14 is out. Does it solve this problem? I prefer to wait for confirmations before upgrading.

**Comment by dinhngocvuong** [comment]
Confirmed fixed for me in 1.0.14

**Comment by edh72** [comment]
confirmed fixed in 1.0.14 (coming from .8)

**Comment by hocza** [comment]
```
manifest.js?id=2d315777967b6001bcf1:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at t (manifest.js?id=2d315777967b6001bcf1:1)
    at Object.<anonymous> (app.js?id=5a12a2096a117db587e7:1)
    at t (manifest.js?id=2d315777967b6001bcf1:1)
    at Object.<anonymous> (app.js?id=5a12a2096a117db587e7:1)
    at t (manifest.js?id=2d315777967b6001bcf1:1)
    at window.webpackJsonp (manifest.js?id=2d315777967b6001bcf1:1)
    at app.js?id=5a12a2096a117db587e7:1
t @ manifest.js?id=2d315777967b6001bcf1:1
(anonymous) @ app.js?id=5a12a2096a117db587e7:1
t @ manifest.js?id=2d315777967b6001bcf1:1
(anonymous) @ app.js?id=5a12a2096a117db587e7:1
t @ manifest.js?id=2d315777967b6001bcf1:1
window.webpackJsonp @ manifest.js?id=2d315777967b6001bcf1:1
(anonymous) @ app.js?id=5a12a2096a117db587e7:1
workouts:156 Uncaught ReferenceError: CreateNova is not defined
    at workouts:156
```

Upgraded to 1.0.14. but still broken.

**Comment by AhmedFawzy** [comment]
This error is back again v1.0.15 and also v1.0.16 @themsaid @taylorotwell

**Comment by paras-malhotra** [comment]
@AhmedFawzy both versions work fine for me. Did you make sure to run the Artisan `nova:publish` command?

**Comment by AhmedFawzy** [comment]
@paras-malhotra Yes but now after a lot of testing I figure out that it was a browser cache issue and solved after clearing my browser cache.
So it's working now

**Comment by phoenixg** [comment]
> 1. vendor/laravel/nova

→ npm install
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 13.267s

**Comment by phoenixg** [comment]
@bluec still not working after doing the 6 steps in v1.0.16

**Comment by shenryuken** [comment]
i'm also have the same problem both in windows 10 and ubuntu 16.04 os:
ReferenceError: CreateNova is not defined[Learn More] nova:130:9
<anonymous>
http://localhost/nova-skg/public/nova:130:9
[Show/hide message details.] ReferenceError: Nova is not defined[Learn More]

**Comment by davidhemphill** [comment]
Make sure to run `php artisan nova:publish --force` to get the latest assets after update.

**Comment by shenryuken** [comment]
> 
> 
> Make sure to run `php artisan nova:publish --force` to get the latest assets after update.

Fixed with version 1.0.17...Thanks Nova

**Comment by rick-hidef** [comment]
I ran into this issue after upgrading from 1.1.3 to 1.1.4. The fix from @bluec and @rickmacgillis worked for me, with the change of the path public/nova-assets to /public/vendor/nova
