### ISSUE TITLE
Default search should be case insentitive

### ISSUE THREAD

**Issue by rwdim** [laravel/nova-issues#509]
When we search for users in the User resource (or any), it finds Brian, but not brian... Search should be case-insensitive by default (ilike vs like).  

This applies to Scout searches as well if possible.

**Comment by chescos** [comment]
Are you using MySQL or PostgreSQL?

**Comment by rwdim** [comment]
PostgreSQL

**Comment by rwdim** [comment]
I did not.. Its on my list but low..

Tried indexQuery and that doesnt seem to get called.. I pushed it back on my list to look into. Later.

**Comment by rwdim** [comment]
Excellent info.. I'll look into it.. thx!

**Comment by taylorotwell** [comment]
Fixed in upcoming release.

**Comment by fede91it** [comment]
The issue is still present if you search onto json columns.

The collation set on the table/column is case insensitive.

**Comment by chrisswany** [comment]
Still an issue for me on 1.3.2 with Maria DB and Mysql.

**Comment by AbanoubNassem** [comment]
any news , or work around this issue ?

**Comment by f-liva** [comment]
From September 2018 no news
