### ISSUE TITLE
Pagination - No comments match the given criteria

### ISSUE THREAD

**Issue by mic2100** [laravel/nova-issues#5350]
- Laravel Version: 9.52.0
- Nova Version: 4.22.0
- PHP Version: 8.2.2
- Database Driver & Version:
- Operating System and Version: Debian 11
- Browser type and version: all browsers

### Description:
When navigating to a tabled page with only one result and deleting this entry the page number stays in the URL and doesn't return any results. This makes the table look as though there are no results at all, and there is no way to navigate to one of the other pages. You would need to either navigate away from the page and go back to it by clicking the link again, or you would need to remove the page number from the query params and reload the page

### Detailed steps to reproduce the issue on a fresh Nova installation:

Post -> has many -> Comments

_The has many field will show 5 per page by default on the table_
If you add in 6, 11, 16, 21, 26, 31 etc etc entries
Navigate to the last page in the table
Delete the last entry
When it tries to reload the table you will see the message 'No comments match the given criteria'

This is wrong because there are entries but they are on pages that exist before the one in the URL.

**Comment by crynobone** [comment]
We just released a fix under 4.22.0, are you sure you have the latest assets?

Otherwise, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by mic2100** [comment]
Ah it would appear that whomeever did the upgrade to 4.22.0 didn't publish the resouces! It does still show the message about 'No comments match the given criteria' but the previous button is visible, so you can navigate back now
