### ISSUE TITLE
Turn off autofill for password field

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#582]
![autocomplete](https://user-images.githubusercontent.com/29180903/45598858-33d85b80-b9b0-11e8-84d1-b2db8bced8d0.png)

Seems as though chrome is treating the create form as a login form regarding autofill

[MDN: How to Turn Off Form Autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion)

autocomplete="off" may not work in logins, per that article
autocomplete="new-password" for password inputs

I would say turning it off for all fields, but thats opinionated

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by mattsims** [comment]
It would be great to have the option to disable this for any field type on a per-instance basis, as I'm finding that Chrome's autocomplete gets in the way of the date picker UI. Something like the following would be great:

`Date::make('Date')->format('DD/MM/YY')->disableAutocomplete()`

**Comment by dillingham** [comment]
@davidhemphill Im still getting autocomplete in chrome on users/new

**Comment by dillingham** [comment]
![ugh](https://user-images.githubusercontent.com/29180903/45960464-4d018d80-bfea-11e8-970a-27de3e253f4a.png)

Kind of sucks to erase email and password to create new users each time :/

**Comment by fletch3555** [comment]
That's likely Lastpass' "Auto-fill" feature (or another similar password manager), not the browser auto-complete.  Lastpass doesn't respect the `autocomplete` attribute, and instead requires it's own `data-lpignore=true` attribute (https://lastpass.com/support.php?cmd=showfaq&id=10512)

**Comment by dillingham** [comment]
@fletch3555 I dont use any password managers though 🤔

**Comment by davidhemphill** [comment]
@dillingham ok, just went another level deeper and added `autocomplete="off"` for each inside Nova. This should take care of it. Should come out in the next release.

**Comment by dillingham** [comment]
@davidhemphill thanks!

**Comment by fbingha** [comment]
Still seeing the password filled in with autocomplete.

Using Nova 1.1.9 and Chrome 70.0.3538.110 (Official Build) (64-bit)

Inspecting the password input, I do see that it has autocomplete="off" defined.

**Comment by FrittenKeeZ** [comment]
This seems to still be a problem.
https://bugs.chromium.org/p/chromium/issues/detail?id=914451&can=2&q=Autofill%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by FrittenKeeZ** [comment]
@davidhemphill as mentioned in #1438 password fields need to use `autocomplete="new-password"` for it to work properly.

**Comment by davidhemphill** [comment]
Fixed for password fields in https://github.com/laravel/nova/commit/122bc5b2d56d2a98d88d98f77800bd5a1ca7a5c8

**Comment by stuartcusackie** [comment]
> That's likely Lastpass' "Auto-fill" feature (or another similar password manager), not the browser auto-complete. Lastpass doesn't respect the `autocomplete` attribute, and instead requires it's own `data-lpignore=true` attribute (https://lastpass.com/support.php?cmd=showfaq&id=10512)

Yep. Unfortunately I can't control what extensions my users use, so hopefully this fixes the LastPass extension, which was adding populating the logged in user's email address into Nova email fields:

```
->withMeta([
     'extraAttributes' => [
        'data-lpignore' => 'true',
     ],
]),
```

**Comment by dan-lutd** [comment]
I'm running into the lastpass issue with the password field,
email field was experencing the same thing until I tried @stuartcusackie 
`->withMeta([
     'extraAttributes' => [
        'data-lpignore' => 'true',
     ],
]),
`

Can ->withMeta be added to password field so we can prevent data corruption? 
[See Issue 3271](https://github.com/laravel/nova-issues/issues/3271#issue-819068348)

@stuartcusackie @bdelamatre Any work arounds?

**Comment by dan-lutd** [comment]
Lastpass user needs to have this option enabled:

Account Options > Extension Preferences > Advanced > Respect AutoComplete=off: allow websites to disable Autofill
