### ISSUE TITLE
Image field "values" don't persist on update after initial upload when used with a Repeater

### ISSUE THREAD

**Issue by arneau** [laravel/nova-issues#6015]
- Laravel Version: 10.30.0
- Nova Version: 4.29.0

### Description:

As per this issue's title, it appears as though Image field "values", when used in conjunction with Repeater fields, don't persist. I realise that Repeater fields are still in beta, but don't see anything in the documentation at https://nova.laravel.com/docs/resources/repeater-fields.html covering that.

My table structure is as follows ...

```
products
- id

product_images
- id
- description
- image
- product_id
```

My classes are as follows ...

app/Models/Product.php:
```
<?php

namespace App\Models;

...

class Product extends Model
{
    ...

    public function images()
    {
        return $this->hasMany(ProductImage::class);
    }

    ...
}
```

app/Models/ProductImage.php:
```
<?php

namespace App\Models;

...

class ProductImage extends Model
{
}
```

app/Nova/Product.php:
```
<?php

namespace App\Nova;

...

class Product extends Resource
{
    ...

    public function fields(NovaRequest $request)
    {
        return [
            ...
            new Panel('Images', [
                Repeater::make('Images')->repeatables([
                    ProductImage::make(),
                ])->asHasMany(),
            ]),
            ...
        ];
    }
```

app/Nova/Repeater/ProductImage.php:
```
<?php

namespace App\Nova\Repeater;

...

class ProductImage extends Repeatable
{
    public static $model = \App\Models\ProductImage::class;

    public function fields(NovaRequest $request)
    {
        return [
            ID::make(),
            Text::make('Description')->rules('max:255'),
            Image::make('Image')->deletable(false)->disk('public'),
        ];
    }
}

```

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Add a product image (repeatable) ...
![Screenshot 2023-11-01 at 14 25 39](https://github.com/laravel/nova-issues/assets/15026566/a001dbac-b9c0-431a-a33c-8fb9fd9c8e57)

2. Select image (file) ...
![Screenshot 2023-11-01 at 15 09 28](https://github.com/laravel/nova-issues/assets/15026566/ec67f2f6-9aae-4142-813a-86bd95dba262)

3. Update product (model) ...
![Screenshot 2023-11-01 at 14 27 38](https://github.com/laravel/nova-issues/assets/15026566/281b892c-3d99-46c5-84c0-38762a660db4)

4. Confirm `product_images`.`image` column contains correct value ...
![Screenshot 2023-11-01 at 15 10 54](https://github.com/laravel/nova-issues/assets/15026566/96f1e2bc-f539-4015-a75b-95d95361b5f8)

5. Update product (model) again ...
![Screenshot 2023-11-01 at 15 11 39](https://github.com/laravel/nova-issues/assets/15026566/5ff22434-7ca1-49d8-90cd-2afac1857302)

6. Notice the `product_images`.`image` column no longer has a value ...
![Screenshot 2023-11-01 at 15 12 15](https://github.com/laravel/nova-issues/assets/15026566/cbb0a6a7-1640-4e15-946d-53be788c2fa8)

### In closing

I suspect that the `image` column's value is empty after subsequent saves because those rows are deleted and recreated (as per https://nova.laravel.com/docs/resources/repeater-fields.html#upserting-repeatables-using-unique-fields), for some reason the original value isn't included in the XHR payload, and it looks like that image attribute will therefore only be "filled" if a new file is uploaded.

![Screenshot 2023-11-01 at 15 21 14](https://github.com/laravel/nova-issues/assets/15026566/85e6c552-0a36-4126-bd12-d7d2fefb43b1)

I have been able to get that `image` column's values to persist by specifying a unique field so that upserts are run instead (ie. `->uniqueField('uuid')`), but then the reordering of images (repeatables) no longer work.

**Comment by KrendiL101** [comment]
It is still not resolved, can't save image in repeatable after first save. Also, when saving two images in repeatable, the same error

**Comment by christian-heiko** [comment]
Any updates or timeline on this?

**Comment by RomainMazB** [comment]
Absolutely not a final solution but I've searched where the issue was and it's kind of complex.

My use case is using the JSON preset and to me, the issue come from the fact that a clean Fluent is created inside of the preset, meaning that the File field can't keep track of a precedent eventual value of the field.

ATM for those who really need to keep files data after an update request, I've found this temporary solution:

I create a custom preset to override the JSON one and commented the line who reset the repeater field value.
```php
class CustomJSON extends JSON
{
    /**
     * Save the field value to permanent storage.
     *
     * @param  string|null  $uniqueField
     * @return \Closure
     */
    public function set(
        NovaRequest $request,
        string $requestAttribute,
        Model $model,
        string $attribute,
        RepeatableCollection $repeatables,
        $uniqueField
    ) {
        // Reset the field attribute in case it's filled already
        $model->setAttribute($attribute, null); // <<<< ---- Here, comment this line

        $fieldCallbacks = collect($request->input($requestAttribute));
        // ...
```

Hoping that get fixed by a proper solution quickly 🤞🏻.

**Comment by schniper** [comment]
Here is my approach, which doesn't require modifying other files and may even be easy to integrate in the framework:

Add a hidden field to your Repeatable:
`Hidden::make('Key')
                ->default(fn () => uniqid()),`

In your model, do something on the lines of
`protected static function boot()
    {
        parent::boot();

        static::updating(function ($model) {
            $originalDocuments = Arr::keyBy($model->getOriginal('documents'), 'fields.key');

            $model->documents = Arr::map($model->documents, function ($document) use ($originalDocuments) {
                if (! empty($document['fields']['file'])) {
                    return $document;
                }

                if (! isset($originalDocuments[$document['fields']['key']])) {
                    return $document;
                }

                $document['fields']['file'] = $originalDocuments[$document['fields']['key']]['fields']['file'] ?? '';

                return $document;
            });
        });
    }`

This assumes my DB json field is called documents, and my repeatable has a file field called "file", which I want to retain.
As it probably is obvious, I am using those generated keys to put back the file paths, when updating the model.

**Comment by AbdullahGhanem** [comment]
Fixed by this section [Link](https://nova.laravel.com/docs/resources/repeater-fields.html#upserting-repeatables-using-unique-fields)

just add **->uniqueField('id')**
```
Repeater::make('Line Items')
  ->asHasMany()
  ->uniqueField('id')
  ->repeatables([
  \App\Nova\Repeater\LineItem::make()
  ])
```
and add **ID::hidden(),** // The unique ID field

**Comment by KrendiL101** [comment]
> Fixed by this section [Link](https://nova.laravel.com/docs/resources/repeater-fields.html#upserting-repeatables-using-unique-fields)
> 
> just add **->uniqueField('id')**
> 
> ```
> Repeater::make('Line Items')
>   ->asHasMany()
>   ->uniqueField('id')
>   ->repeatables([
>   \App\Nova\Repeater\LineItem::make()
>   ])
> ```
> 
> and add **ID::hidden(),** // The unique ID field

This is working perfect, thanks!

**Comment by philipdowner** [comment]
> Fixed by this section [Link](https://nova.laravel.com/docs/resources/repeater-fields.html#upserting-repeatables-using-unique-fields)
> 
> just add **->uniqueField('id')**
> 
> ```
> Repeater::make('Line Items')
>   ->asHasMany()
>   ->uniqueField('id')
>   ->repeatables([
>   \App\Nova\Repeater\LineItem::make()
>   ])
> ```
> 
> and add **ID::hidden(),** // The unique ID field

Agree that this works when using a distinct model via the `asHasMany()` method, but the issue still persists when storing the data as JSON. For example, my model has an `images` JSON column, and the repeater allows the storage of `path`, `caption`, and `alt_text` fields.

**Comment by tonnyorg** [comment]
Looks like I have the same problem: #6410

**Comment by tonnyorg** [comment]
Any ETA on this?

**Comment by jeremynikolic** [comment]
Hi @tonnyorg, we are working on the next version, Nova 5 which will contain this fix. 
No set ETA yet but very soon, which is why we decided not to add beta related fixes to 4👍

**Comment by tonnyorg** [comment]
@jeremynikolic ahhh got it, tyvm!

**Comment by crynobone** [comment]
Released with Laravel Nova 5.0.0

Feel free to open up a new issue if you're still experiencing this problem on the latest version.

**Comment by Kristories** [comment]
I noticed there's still an issue with Laravel Nova v5 that might need documentation. For example, using this approach won't let you update:

```php
use App\Nova\Repeater\Talents\Images;

Repeater::make('Gallery', 'images')
    ->repeatables([
        Images::make(),
    ])->asJson(),
```
```php
public function fields(NovaRequest $request)
{
    return [
        Image::make('Photo')
            ->path('galleries')
            ->disk('public')
            ->required(),
    ];
}
```
```json
[
  {
    "type": "image",
    "fields": {
      "photo": "galleries/m7D9ZEgB9A4W7HSNAYhTRik41P4IuUwGFsMNWNj8.png"
    }
  },
  {
    "type": "image"
  }
]
```

However, it works perfectly if you do it like this:

```php
use App\Nova\Repeater\Talents\Images;

Repeater::make('Gallery', 'images')
    ->uniqueField('id') // Add uniqueField
    ->repeatables([
        Images::make(),
    ])->asJson(),
```
```php
public function fields(NovaRequest $request)
{
    return [
        Hidden::make('ID', 'id'), // Add hidden field
        Image::make('Photo')
            ->path('galleries')
            ->disk('public')
            ->required(),
    ];
}
```

```json
[
  {
    "type": "image",
    "fields": {
      "id": "9770ae3a-d39a-4a18-ab7a-e8c5318c0c66",
      "photo": "galleries/m7D9ZEgB9A4W7HSNAYhTRik41P4IuUwGFsMNWNj8.png"
    }
  },
  {
    "type": "image",
    "fields": {
      "id": "ad6ca60e-83e5-4c4a-b9c2-02abc7d7592a",
      "photo": "galleries/Gr3Uykd1tjjimCD3tllcVnfaQT9wQsJbvbVGQFyP.png"
    }
  }
]
```

**Comment by FaridAghili** [comment]
@Kristories Your approach works but still has some bugs.

- If you delete the model, it's images won't be deleted when Image field is set as `prunable()`.
- if you add multiple items, and reorder them, a new image will be stored on disk, for each reordered image, and old image won't be deleted.
- If you set image field as `required`, it's always required, so you can update your resource, because of the required validation error.

Couldn't find a workaround yet.

**Comment by tonnyorg** [comment]
@crynobone the issue still persist, if you define this repeatable it still fails:
```
<?php

namespace App\Nova\Repeaters;

use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Fields\Image;
use Laravel\Nova\Fields\Repeater\Repeatable;
use Laravel\Nova\Fields\Text;

class DevelopmentPictureRepeater extends Repeatable
{
	/**
	 * Get the fields displayed by the repeatable.
	 *
	 * @return array<int, \Laravel\Nova\Fields\Field>
	 */
	public function fields(NovaRequest $request): array
	{
		return [
            Image::make('Imágen', 'fileName')
                ->disk('public')
                ->required(),

			Text::make('Nombre', 'name')
                ->required(),
		];
	}
}
```

**Comment by crynobone** [comment]
![Screenshot_20250110_124738_Chrome.png](https://github.com/user-attachments/assets/76868496-d44f-4283-aabb-7790c4068508)

**Comment by tonnyorg** [comment]
@crynobone my bad, ty for that it works now!

**Comment by MattRogowski** [comment]
Here in June 2025 and this is still an issue when storing as JSON.

I can't easily store the repeaters with asHasMany() and I can't set the field to be required as you have to upload it again every time you edit the resource. I don't understand why this was closed.

Edit: for others with the problem, where the docs say to use `ID::hidden('uuid')` for the unique field, try using `ID::hidden('uuid', 'uuid')` - with just `ID::hidden('uuid')` it was setting `"id": null` in the JSON, with `ID::hidden('uuid', 'uuid')` it set `"uuid": "67b6d14f-9075-463e-86de-778d60a151ab"`

**Comment by crynobone** [comment]
@MattRogowski best to create a new issue with a reproducing repository so we can have a look. As you can see from above, the issue is fixed without any code changes in `laravel/nova`.

**Comment by vbezruchkin** [comment]
> ![Screenshot_20250110_124738_Chrome.png](https://github.com/user-attachments/assets/76868496-d44f-4283-aabb-7790c4068508)

Thanks for this. Also got stuck with the implementation until I found this thread!
