### ISSUE TITLE
Relatable validation error

### ISSUE THREAD

**Issue by gonzunigad** [laravel/nova-issues#624]
I have a Workers Resource and Person Resource. 

Some persons can be workers. In that case, the person `HasOne` Worker relation. 
(workers table has a person_id)

**The problem is:**
Nova/Person
![image](https://user-images.githubusercontent.com/1103494/45851783-f9095700-bd12-11e8-941f-1b0608c850a4.png)

Nova/Worker
![image](https://user-images.githubusercontent.com/1103494/45851792-00c8fb80-bd13-11e8-9641-a96467102006.png)

When I try to update the worker, `relatable` validation throws an error. 
![image](https://user-images.githubusercontent.com/1103494/45851671-7e403c00-bd12-11e8-842e-06f74f23375d.png)

If i change `HasOne` field to `HasMany` (not what I need) it does not throw that exception and I can save my worker resource. 

I think that the validations should check if `count() > 1 `when updating or something like this. 
![image](https://user-images.githubusercontent.com/1103494/45851711-b34c8e80-bd12-11e8-92dd-c8dd2e9ddb49.png)

**Comment by taylorotwell** [comment]
If you check for > 1 won't that let you attach two records to a has one relationship?

**Comment by gonzunigad** [comment]
I think, the problem is that when you are **updating** the resource, you already had one record. (the record that is being updated itself). 
Maybe it should exclude the current resource id from the count(). 🤷🏻‍♂️

**Comment by gonzunigad** [comment]
https://gist.github.com/gonzunigad/e810841751d2ba7c3a2d78c83dae80fa

**Comment by taylorotwell** [comment]
If you follow my simple example of a Post that belongs to a user and a user has many posts, do you get the error?

**Comment by kendugu** [comment]
I'm also experiencing this- if it helps, see also #227 and https://github.com/laravel/nova-docs/issues/50.

**Comment by taylorotwell** [comment]
OK I can recreate it now. Looking into it.

**Comment by taylorotwell** [comment]
Fixed in upcoming release.

**Comment by SerhiiStarovoitov** [comment]
It looks like there is a one more issue here.

`$model = $this->query->select('*')->whereKey($value)->first();`

On line #49 in src/Rules/Relatable.php passes() method we're modifying $this->query with select(*) method, so if the query contains some bindings (from $with or $withCount original model properties, for example), they are overwritten, but bindings are left the same. That's why a new query is running with the old bindings and we're getting wrong query results (and passes method returns false so we're getting "Relatable validation error"). If the original query got no any bindings everything is fine.

@taylorotwell

**Comment by radd2004** [comment]
Is this issue released, since this ticket is closed?
Running 1.1.8 and still experiencing the issue.

**Comment by h-zone** [comment]
@taylorotwell ?
2.0.0 > "This category may not be associated with this resource."

Categories 
`id | parent_id | title`

Service (attachable to category)
`id | category_id | title`

Categories works fine
Services without categories works fine

Declarations in both ways hasMany at Categories and belongsTo at Services work without any notices
But categories is not attaches to the new Service. Or attaches not last level (by parent_id), and i have no any customizations in Models:
simple
`return $this->hasMany( Services::class, 'category_id');`
and
`return $this->belongsTo( Category::class, 'category_id' );`

**Comment by Frozire** [comment]
@h-zone Having the same problem. Did you find a solution?

**Comment by h-zone** [comment]
work through select

**Comment by Frozire** [comment]
> work through select

For anyone else finding this - using select you can do the following.


```
public function fields(Request $request)
{
    return [
        Select::make('Podcast', 'podcast_id')
            ->options(\App\Podcast::all()->pluck('title', 'id'))
            ->hideFromIndex()
            ->hideFromDetail(),
        BelongsTo::make('Podcast')
            ->hideWhenUpdating()
            ->hideWhenCreating(),
    ];
}
```

**Comment by Landish** [comment]
@Frozire Thanks, your solution worked. 

But, this issue still exists in:
Nova: 2.12.0
Laravel: 6.18.3

However, on local (valet) it works fine, it has problems only on production deployed with Forge on AWS.
