### ISSUE TITLE
hello, I have a int weight field , default value is 0, when I update item, show errors blow!

### ISSUE THREAD

**Issue by guoxiangke** [laravel/nova-issues#893]
> ERROR:SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'weight' cannot be null (SQL: update

I aslo added `protected $attributes = [
      'weight' => 0,
    ];` to the model.
![image](https://user-images.githubusercontent.com/1160703/47481720-1f1c9c80-d867-11e8-8371-77274ea49aa6.png)
$table->integer('weight')->default(0);
seems the form ajax submit didn't send the value 0

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the current release.

**Comment by guoxiangke** [comment]
![image](https://user-images.githubusercontent.com/1160703/47598608-b94c2400-d9d0-11e8-960e-8c9869673e3c.png)

seems not fixed yet, I already update nova

**Comment by rjksn** [comment]
I'm on the current release (1.1.7) and am dealing with this issue. What was the fix? 

I see mention of adding to the default attributes, but this does not have a model. It's a pivot table on a join of two models. The database is set to default to "0". 

            // Associations
            BelongsToMany::make('Clients')->fields(function () {
                return [
                    Number::make('Budget'),
                    Number::make('Spend'),
                ];
            })->sortable(),
