### ISSUE TITLE
Input label "for" attribute is missing

### ISSUE THREAD

**Issue by rrdial** [laravel/nova-issues#946]
- Laravel Version: 5.6.39
- Nova Version: 1.1.7
- PHP Version: 7.1.23

### Description:
The `for` attribute is _missing_ on `<label>`s when the corresponding input already has a value.
The `for` attribute is set on `<label>`s that do not have a value saved in the database.

![screenshot 2018-11-06 09 04 33](https://user-images.githubusercontent.com/1458388/48070672-6b8ca400-e1a6-11e8-9623-66744269968f.png)

### Steps To Reproduce:
1. Create Resource with at least two Nova Field elements.
2. Fill in one of the Fields and save the record.
3. Edit the record. Notice that the Field with a value stored in the database no longer has a `<label>` with a `for=` attribute, and clicking on the label will not focus the input.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by rrdial** [comment]
@davidhemphill, I just updated to Nova 1.1.8 and the `for` attribute is still missing when the corresponding input has a non-empty value on page load.

**Comment by rrdial** [comment]
I just updated to **Nova 1.2.0** and this issue still exists.

**Comment by davidhemphill** [comment]
Just merged a PR that should actually fix this 👍

**Comment by rrdial** [comment]
I just updated to **Nova 1.2.0** and can confirm that this is fixed. Thank you @davidhemphill !
